// ═══════════════════════════════════════════════
// Country Comparison Data
// Compares AI tool availability, pricing, and
// ecosystem across key Asian markets.
// ═══════════════════════════════════════════════

export interface CountryComparison {
  slug: string;
  country: string;
  capital: string;
  region: 'Southeast Asia' | 'East Asia' | 'South Asia';
  currency: string;
  currencyCode: string;
  language: string;
  population: string;
  gdpPerCapita: string; // USD
  internetPenetration: string;
  englishProficiency: string; // EPI score or description
  startupEcosystem: string; // description
  topAITools: string[];
  localAIScene: string;
  pricingNote: string;
  strengths: string[];
  challenges: string[];
  overallScore: number; // 1-10 for AI readiness
  flagEmoji: string;
}

export const countryComparisons: CountryComparison[] = [
  {
    slug: 'singapore',
    country: 'Singapore',
    capital: 'Singapore',
    region: 'Southeast Asia',
    currency: 'Singapore Dollar',
    currencyCode: 'SGD',
    language: 'English, Mandarin, Malay, Tamil',
    population: '5.7M',
    gdpPerCapita: '$88,000',
    internetPenetration: '92%',
    englishProficiency: 'Very High (EPI #4 globally)',
    startupEcosystem: 'World-class — 15+ unicorns, strong gov grants (SGInnovate, EnterpriseSG)',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'GitHub Copilot', 'Perplexity', 'Midjourney', 'Notion AI', 'Gamma'],
    localAIScene: 'Smart Nation initiative, AI Verify framework, strong research at NUS/NTU, growing ML engineer talent pool.',
    pricingNote: 'Full access to all global tools. USD pricing applies but SGD spending power is high. ~$20/mo tools are affordable.',
    strengths: ['Highest English proficiency in Asia', 'Strong government AI funding', 'Excellent digital infrastructure', 'Pro-business regulatory environment'],
    challenges: ['Small domestic market', 'High cost of living for local talent', 'Dependence on foreign tech talent'],
    overallScore: 9.2,
    flagEmoji: '🇸🇬',
  },
  {
    slug: 'malaysia',
    country: 'Malaysia',
    capital: 'Kuala Lumpur',
    region: 'Southeast Asia',
    currency: 'Malaysian Ringgit',
    currencyCode: 'MYR',
    language: 'Malay, English, Mandarin, Tamil',
    population: '34M',
    gdpPerCapita: '$13,000',
    internetPenetration: '89%',
    englishProficiency: 'Moderate (EPI #25)',
    startupEcosystem: 'Growing — MyDigital, MDEC initiatives, booming e-commerce and fintech in KL and Penang',
    topAITools: ['ChatGPT', 'Gemini', 'GitHub Copilot', 'Canva AI', 'Perplexity', 'Gamma'],
    localAIScene: 'MDEC-driven AI adoption, focus on Islamic fintech AI, growing data centre hubs (Johor). English is widely used in tech.',
    pricingNote: 'USD tools cost ~3x in purchasing power. Free/freemium tools (Gemini, Perplexity) are popular. ~$20/mo is a significant expense.',
    strengths: ['Strong English literacy in tech', 'Cost-effective talent', 'Government AI incentives', 'Growing data centre infrastructure'],
    challenges: ['Currency depreciation against USD', 'Brain drain to Singapore', 'Regulatory uncertainty in AI governance'],
    overallScore: 7.5,
    flagEmoji: '🇲🇾',
  },
  {
    slug: 'indonesia',
    country: 'Indonesia',
    capital: 'Jakarta',
    region: 'Southeast Asia',
    currency: 'Indonesian Rupiah',
    currencyCode: 'IDR',
    language: 'Indonesian (Bahasa Indonesia)',
    population: '280M',
    gdpPerCapita: '$5,100',
    internetPenetration: '79%',
    englishProficiency: 'Low (EPI #74)',
    startupEcosystem: 'Vibrant — GoTo, Traveloka, 10+ unicorns. Growing AI hubs in Jakarta, Bandung, and Jogja.',
    topAITools: ['Gemini', 'ChatGPT', 'Canva AI', 'Perplexity', 'Gamma'],
    localAIScene: 'Pemerintah supports AI via Kominfo. Bahasa NLP is challenging — limited training data. Mobile-first AI adoption on WhatsApp bots.',
    pricingNote: '$20/mo is ~IDR 325K — a week\'s groceries. Free tools dominate (Gemini is #1). Mobile-only users rely on free tiers heavily.',
    strengths: ['Massive domestic market', 'Mobile-first digital economy', 'Growing developer community', 'Young, tech-savvy population'],
    challenges: ['Low English proficiency limits tool access', 'Currency weakness vs USD', 'Infrastructure gaps outside Java', 'AI talent shortage'],
    overallScore: 6.8,
    flagEmoji: '🇮🇩',
  },
  {
    slug: 'thailand',
    country: 'Thailand',
    capital: 'Bangkok',
    region: 'Southeast Asia',
    currency: 'Thai Baht',
    currencyCode: 'THB',
    language: 'Thai',
    population: '72M',
    gdpPerCapita: '$7,200',
    internetPenetration: '85%',
    englishProficiency: 'Low (EPI #97)',
    startupEcosystem: 'Emerging — hubs in Bangkok (True Digital Park), government Thailand 4.0 initiative, growing agritech/fintech.',
    topAITools: ['Gemini', 'ChatGPT', 'Canva AI', 'Perplexity', 'Midjourney'],
    localAIScene: 'Thai NLP is developing (PyThaiNLP). Tourism AI (chatbots, translation) is big. LINE ecosystem dominates — AI bots on LINE are common.',
    pricingNote: '$20/mo is ~THB 720 — affordable but not casual. Free tier tools like Gemini are most used. Thai language support is critical.',
    strengths: ['Strong tourism industry for AI use cases', 'Growing digital payment infrastructure', 'Government Thailand 4.0 support', 'Thriving e-commerce'],
    challenges: ['Limited Thai-language AI support', 'Low English proficiency', 'Talent concentrated in Bangkok', 'Regulatory framework evolving'],
    overallScore: 6.5,
    flagEmoji: '🇹🇭',
  },
  {
    slug: 'vietnam',
    country: 'Vietnam',
    capital: 'Hanoi',
    region: 'Southeast Asia',
    currency: 'Vietnamese Dong',
    currencyCode: 'VND',
    language: 'Vietnamese',
    population: '100M',
    gdpPerCapita: '$4,300',
    internetPenetration: '73%',
    englishProficiency: 'Moderate (EPI #58)',
    startupEcosystem: 'Fast-growing — VNG, VNLife, MoMo. Strong developer community, government National Digital Transformation program.',
    topAITools: ['Gemini', 'ChatGPT', 'GitHub Copilot', 'Canva AI', 'Perplexity', 'Claude'],
    localAIScene: 'Vibrant AI dev community (Vietnam AI Festival). Strong in computer vision and NLP. FPT and Vingroup invest heavily in AI R&D.',
    pricingNote: '$20/mo is ~VND 510K — significant for individual users. Copilot is popular among devs. Gemini leads free-tier usage.',
    strengths: ['Strong engineering talent pool', 'Fast-growing digital economy', 'Government digital transformation push', 'Cost-effective AI development'],
    challenges: ['Vietnamese language AI support still maturing', 'Infrastructure gaps in rural areas', 'Low average income limits tool adoption', 'AI ethics framework developing'],
    overallScore: 7.0,
    flagEmoji: '🇻🇳',
  },
  {
    slug: 'philippines',
    country: 'Philippines',
    capital: 'Manila',
    region: 'Southeast Asia',
    currency: 'Philippine Peso',
    currencyCode: 'PHP',
    language: 'Filipino (Tagalog), English',
    population: '116M',
    gdpPerCapita: '$3,900',
    internetPenetration: '68%',
    englishProficiency: 'High (EPI #20 — highest in SEA after SG)',
    startupEcosystem: 'Emerging — hubs in Manila and Cebu. BPO-driven economy transitioning to tech. GCash and PayMaya lead fintech.',
    topAITools: ['ChatGPT', 'Gemini', 'Canva AI', 'Midjourney', 'Gamma', 'Perplexity'],
    localAIScene: 'Strong English proficiency makes global tools accessible. BPO industry drives AI adoption (automation, chatbots). Growing AI dev community.',
    pricingNote: '$20/mo is ~PHP 1,150 — manageable for professionals but not mass-market. English interface means no language barrier.',
    strengths: ['High English proficiency (3rd in Asia)', 'Large young population', 'Strong BPO/AI synergy', 'Growing startup funding'],
    challenges: ['Infrastructure gaps outside Metro Manila', 'Low internet penetration in provinces', 'Currency volatility', 'Brain drain to US and SG'],
    overallScore: 7.2,
    flagEmoji: '🇵🇭',
  },
  {
    slug: 'hong-kong',
    country: 'Hong Kong',
    capital: 'Hong Kong',
    region: 'East Asia',
    currency: 'Hong Kong Dollar',
    currencyCode: 'HKD',
    language: 'Chinese (Cantonese), English',
    population: '7.5M',
    gdpPerCapita: '$50,000',
    internetPenetration: '93%',
    englishProficiency: 'Very High (EPI #32)',
    startupEcosystem: 'Strong — HKSTP, Cyberport, active VC scene. Gateway to China for international startups. Growing fintech and AI.',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'GitHub Copilot', 'Perplexity', 'Notion AI', 'Cursor', 'Gamma'],
    localAIScene: 'Strong university AI research (HKU, CUHK, HKUST). Cyberport AI Hub. Cross-border AI with Greater Bay Area initiatives.',
    pricingNote: 'Full access to all tools. HKD spending power is high. $20/mo is easily affordable. Chinese language tools (DeepSeek) also popular.',
    strengths: ['Excellent digital infrastructure', 'Bilingual talent (Chinese + English)', 'Strong university AI research', 'Proximity to Shenzhen tech ecosystem'],
    challenges: ['Small talent pool', 'High operating costs', 'Political uncertainty affecting talent retention', 'Competition from Shenzhen'],
    overallScore: 8.8,
    flagEmoji: '🇭🇰',
  },
  {
    slug: 'taiwan',
    country: 'Taiwan',
    capital: 'Taipei',
    region: 'East Asia',
    currency: 'New Taiwan Dollar',
    currencyCode: 'TWD',
    language: 'Chinese (Mandarin), Taiwanese Hokkien',
    population: '23.4M',
    gdpPerCapita: '$33,000',
    internetPenetration: '90%',
    englishProficiency: 'Moderate (EPI #40)',
    startupEcosystem: 'Robust — TSMC-driven hardware ecosystem. Growing AI startups in Taipei (Appier, Gogolook). Strong semiconductor AI synergy.',
    topAITools: ['ChatGPT', 'Gemini', 'Claude', 'GitHub Copilot', 'Midjourney', 'DeepSeek', 'Perplexity'],
    localAIScene: 'Hardware AI (semiconductors, edge AI) is world-class. Software AI growing. Mandarin-first tool adoption. DeepSeek popular for Chinese tasks.',
    pricingNote: 'USD tools are accessible. TWD spending power moderate. Both English and Chinese interfaces work. DeepSeek offers free alternative.',
    strengths: ['Semiconductor AI leadership', 'Strong manufacturing automation', 'Excellent R&D culture', 'High internet penetration'],
    challenges: ['Geopolitical uncertainty', 'Limited domestic market size', 'Talent competition with chip industry', 'AI regulation evolving'],
    overallScore: 8.2,
    flagEmoji: '🇹🇼',
  },
  {
    slug: 'south-korea',
    country: 'South Korea',
    capital: 'Seoul',
    region: 'East Asia',
    currency: 'South Korean Won',
    currencyCode: 'KRW',
    language: 'Korean',
    population: '52M',
    gdpPerCapita: '$35,000',
    internetPenetration: '97%',
    englishProficiency: 'Moderate (EPI #49)',
    startupEcosystem: 'Dynamic — K-startup program, Pangyo Techno Valley. Strong in AI, gaming (Krafton, Nexon), and fintech (Kakao, Toss).',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'Midjourney', 'GitHub Copilot', 'Perplexity', 'Cursor'],
    localAIScene: 'Korea has world-class AI research (Naver, Kakao, Samsung, KAIST). Korean LLMs (Naver HyperCLOVA) compete globally. Tech-savvy population.',
    pricingNote: 'High spending power. KRW 26K/mo for ChatGPT Plus is accessible. Korean-language AI tools (HyperCLOVA) are strong competitors.',
    strengths: ['World-class internet infrastructure', 'Strong corporate AI investment', 'Tech-obsessed consumer base', 'Excellent gaming/AI crossover'],
    challenges: ['Limited English interface adoption', 'Intense work culture may slow innovation', 'Competition from chaebol-dominated AI', 'Rapidly declining birth rate'],
    overallScore: 8.5,
    flagEmoji: '🇰🇷',
  },
  {
    slug: 'japan',
    country: 'Japan',
    capital: 'Tokyo',
    region: 'East Asia',
    currency: 'Japanese Yen',
    currencyCode: 'JPY',
    language: 'Japanese',
    population: '124M',
    gdpPerCapita: '$35,000',
    internetPenetration: '93%',
    englishProficiency: 'Low (EPI #87)',
    startupEcosystem: 'Growing — J-Startup program, Tokyo AI Lab. Strong in robotics AI, healthcare AI, and manufacturing automation. SoftBank backing.',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'Midjourney', 'GitHub Copilot', 'Notion AI', 'Gamma'],
    localAIScene: 'Japan leads in robotics AI and automation. Japanese LLMs (ELYZA, rinna) gaining traction. Government Society 5.0 promotes AI everywhere.',
    pricingNote: 'JPY weakness makes USD tools pricier. ChatGPT Plus is ~JPY 3,000/mo — accessible but not casual. Japanese-only tools have strong adoption.',
    strengths: ['Robotics AI world leader', 'Strong manufacturing AI', 'Government Society 5.0 funding', 'Aging population creates AI demand'],
    challenges: ['Low English proficiency', 'Conservative corporate adoption', 'Siloed AI research in large corporates', 'Aging workforce limits digital talent'],
    overallScore: 7.8,
    flagEmoji: '🇯🇵',
  },
  {
    slug: 'india',
    country: 'India',
    capital: 'New Delhi',
    region: 'South Asia',
    currency: 'Indian Rupee',
    currencyCode: 'INR',
    language: 'Hindi, English, 22 official languages',
    population: '1.45B',
    gdpPerCapita: '$2,700',
    internetPenetration: '55%',
    englishProficiency: 'Moderate (EPI #60 — but largest English-speaking population in Asia)',
    startupEcosystem: 'Vibrant — 100+ unicorns, Bangalore/Hyderabad AI hubs. World-class talent pool, strong YC presence.',
    topAITools: ['ChatGPT', 'Gemini', 'GitHub Copilot', 'Cursor', 'Claude', 'Perplexity', 'DeepSeek', 'Canva AI', 'Windsurf'],
    localAIScene: 'India is an AI powerhouse — 2nd largest AI talent pool globally. Strong in enterprise AI, SaaS, and AI services. Bhashini for Indian language AI.',
    pricingNote: '$20/mo is ~INR 1,700 — a significant expense. Free tools (Gemini, DeepSeek) are popular. Enterprise plans via India-specific pricing helps.',
    strengths: ['Massive AI talent pool', 'English proficiency for global tools', 'Cost-effective AI development', 'Strong SaaS ecosystem'],
    challenges: ['Infrastructure gaps in tier-2 cities', 'AI regulation still developing', 'Income inequality limits mass adoption', 'Multiple languages challenge local AI'],
    overallScore: 8.0,
    flagEmoji: '🇮🇳',
  },
  {
    slug: 'china',
    country: 'China',
    capital: 'Beijing',
    region: 'East Asia',
    currency: 'Chinese Yuan (Renminbi)',
    currencyCode: 'CNY',
    language: 'Chinese (Mandarin)',
    population: '1.42B',
    gdpPerCapita: '$12,700',
    internetPenetration: '76%',
    englishProficiency: 'Low (EPI #81)',
    startupEcosystem: 'Massive — Shenzhen, Beijing, Shanghai AI hubs. Baidu, Alibaba, Tencent (BAT) lead. DeepSeek, Zhipu, and Moonshot rising.',
    topAITools: ['DeepSeek', 'Baidu ERNIE', 'Alibaba Tongyi Qianwen', 'Tencent Hunyuan', 'Doubao (ByteDance)', 'Zhipu GLM', 'Moonshot Kimi'],
    localAIScene: 'China competes head-to-head with US AI. DeepSeek V3/R1 rivals GPT-4o. Government AI supremacy push. Great Firewall keeps global tools out.',
    pricingNote: 'Western tools (ChatGPT, Claude) are blocked. Chinese alternatives are mostly free or much cheaper. DeepSeek offers free tier with competitive performance.',
    strengths: ['Massive AI research output', 'Government AI investment at scale', 'Manufacturing AI leadership', 'Dominant domestic AI ecosystem'],
    challenges: ['Great Firewall blocks global tools', 'Censorship affects AI training data', 'Geopolitical tension limits collaboration', 'Export controls on advanced chips'],
    overallScore: 8.5,
    flagEmoji: '🇨🇳',
  },
  {
    slug: 'australia',
    country: 'Australia',
    capital: 'Canberra',
    region: 'Southeast Asia', // Included for regional comparison
    currency: 'Australian Dollar',
    currencyCode: 'AUD',
    language: 'English',
    population: '26.5M',
    gdpPerCapita: '$65,000',
    internetPenetration: '90%',
    englishProficiency: 'Very High (native English)',
    startupEcosystem: 'Mature — Atlassian, Canva, SafetyCulture. Strong AI adoption in mining, agriculture, fintech, and healthcare.',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'GitHub Copilot', 'Cursor', 'Canva AI', 'Midjourney', 'Perplexity', 'Notion AI'],
    localAIScene: 'AI adoption is high across sectors. CSIRO Data61 leads research. Growing AI Safety ecosystem. Canva (Sydney) is the iconic AI-native company.',
    pricingNote: 'Full access at AUD pricing. $20/mo ~AUD 30 — easily affordable for professionals. Australian-dollar billing available for many tools.',
    strengths: ['Native English proficiency', 'High disposable income for tools', 'Strong AI research community', 'Leading in AI safety research'],
    challenges: ['Small domestic market', 'Distance from major tech hubs', 'Talent competition with US tech giants', 'Limited venture capital vs US'],
    overallScore: 8.7,
    flagEmoji: '🇦🇺',
  },
  {
    slug: 'new-zealand',
    country: 'New Zealand',
    capital: 'Wellington',
    region: 'Southeast Asia', // Included for regional comparison
    currency: 'New Zealand Dollar',
    currencyCode: 'NZD',
    language: 'English, Māori',
    population: '5.2M',
    gdpPerCapita: '$48,000',
    internetPenetration: '91%',
    englishProficiency: 'Very High (native English)',
    startupEcosystem: 'Small but high-quality — Rocket Lab, Xero, Vend. Strong in agritech AI, environmental AI, and film VFX AI.',
    topAITools: ['ChatGPT', 'Claude', 'Gemini', 'GitHub Copilot', 'Canva AI', 'Midjourney', 'Perplexity'],
    localAIScene: 'Agritech AI (e.g., HALO for kiwi fruit grading) and environmental monitoring AI. Strong Weta Digital legacy in VFX AI. Growing startup community.',
    pricingNote: 'Full access, NZD pricing. $20/mo ~NZD 33 — affordable. Smaller startup ecosystem means fewer local alternatives.',
    strengths: ['English proficiency', 'Innovation in agritech/ environmental AI', 'High quality of life attracts talent', 'Strong film/TV AI expertise'],
    challenges: ['Very small domestic market', 'Geographic isolation', 'Limited VC funding', 'Talent drain to Australia and US'],
    overallScore: 7.5,
    flagEmoji: '🇳🇿',
  },
];

export const regions = ['Southeast Asia', 'East Asia', 'South Asia'] as const;

export function getCountryBySlug(slug: string): CountryComparison | undefined {
  return countryComparisons.find((c) => c.slug === slug);
}

export function getCountriesByRegion(region: string): CountryComparison[] {
  return countryComparisons.filter((c) => c.region === region);
}
