import { Tool } from './types';

// Seed dataset — 30+ tools covering all major categories
// This simulates the Kaggle dataset import. In production, use Supabase.
export const toolsData: Tool[] = [
  {
    id: '1', slug: 'chatgpt', name: 'ChatGPT', tagline: 'The most versatile AI assistant for daily tasks',
    description: 'Create content, code, research, analyze data, and brainstorm with OpenAI\'s flagship language model.',
    website_url: 'https://chatgpt.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Writing & Content', 'Code & Development', 'Research & Analysis'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 200,
    use_cases: ['Content Creation', 'Code Generation', 'Research', 'Productivity'],
    agent_roles: ['Writing Assistant', 'Code Assistant', 'Research Assistant', 'Personal Assistant'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS', 'Android'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Thai', 'Vietnamese'],
    data_residency: 'Global (US, EU)', local_pricing_asia: false, best_for_asia_use_case: 'Multi-language content creation for Asian markets',
    avg_rating: 4.7, total_ratings: 28450, trending_score: 99, saves_count: 45200,
    how_to_use_guide: 'Start with clear prompts. Use Custom Instructions to set your context. Create GPTs for repeatable workflows.',
    playbook_use_cases: ['Drafting emails in Chinese', 'Translating content across Asian languages', 'Code review', 'Travel itinerary planning'],
    playbook_steps: [{ title: 'Set your context', description: 'Use Custom GPT to define your role, audience, and preferences' }, { title: 'Prompt engineering', description: 'Be specific with tasks, provide examples, iterate on output' }],
    is_published: true, created_at: '2022-11-30', source: 'kaggle',
  },
  {
    id: '2', slug: 'claude', name: 'Claude', tagline: 'Thoughtful AI for complex reasoning and long documents',
    description: 'Anthropic\'s AI assistant known for nuanced reasoning, safety-first design, and massive context windows.',
    website_url: 'https://claude.ai', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Writing & Content', 'Code & Development', 'Research & Analysis'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 200,
    use_cases: ['Content Creation', 'Code Generation', 'Research', 'Data Analysis'],
    agent_roles: ['Writing Assistant', 'Research Assistant', 'Data Analyst'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Long-form document analysis, contract review in Asia',
    avg_rating: 4.8, total_ratings: 18200, trending_score: 95, saves_count: 32100,
    how_to_use_guide: 'Upload documents up to 200K tokens. Use Projects to organize related work. Ask for step-by-step reasoning.',
    playbook_use_cases: ['Analyzing 100-page contracts', 'Research paper summaries', 'Code architecture review', 'Strategic planning'],
    playbook_steps: [{ title: 'Upload documents', description: 'Claude handles massive context — upload full documents' }, { title: 'Ask for analysis', description: 'Request summaries, comparisons, or deep analysis' }],
    is_published: true, created_at: '2023-03-14', source: 'kaggle',
  },
  {
    id: '3', slug: 'gemini', name: 'Gemini', tagline: 'Google\'s multimodal AI with deep search integration',
    description: 'Google\'s most capable AI with native Google ecosystem integration, strong multimodal abilities.',
    website_url: 'https://gemini.google.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Research & Analysis', 'Writing & Content'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Research', 'Content Creation', 'Data Analysis', 'Productivity'],
    agent_roles: ['Research Assistant', 'Personal Assistant', 'Data Analyst'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS', 'Android'],
    asia_score: 10, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi', 'Thai', 'Vietnamese', 'Indonesian'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Best free option for Asian language speakers — supports most Asian languages natively',
    avg_rating: 4.5, total_ratings: 15200, trending_score: 88, saves_count: 28100,
    how_to_use_guide: 'Use deep research mode for complex queries. Leverage Google ecosystem integration for seamless workflows.',
    playbook_use_cases: ['Market research for Asian markets', 'Multi-language translation', 'Google Workspace integration'],
    playbook_steps: [{ title: 'Ask naturally', description: 'Gemini understands conversational queries in many Asian languages' }, { title: 'Use extensions', description: 'Connect to Google Workspace, Maps, Flights for travel planning' }],
    is_published: true, created_at: '2023-12-06', source: 'kaggle',
  },
  {
    id: '4', slug: 'copilot', name: 'GitHub Copilot', tagline: 'AI pair programmer that writes code alongside you',
    description: 'Real-time code suggestions in VS Code, JetBrains, and more. The most popular AI coding assistant.',
    website_url: 'https://github.com/features/copilot', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 39,
    use_cases: ['Code Generation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'Desktop'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: 'Accelerating development for Asian tech teams',
    avg_rating: 4.6, total_ratings: 12300, trending_score: 82, saves_count: 19500,
    how_to_use_guide: 'Install in your IDE. Write comments to describe what you want. Tab to accept suggestions.',
    playbook_use_cases: ['Building web apps faster', 'API development', 'Code refactoring'],
    playbook_steps: [{ title: 'Install extension', description: 'Install Copilot in VS Code, JetBrains, or Neovim' }, { title: 'Describe intent', description: 'Write clear comments or function names for best suggestions' }],
    is_published: true, created_at: '2022-06-21', source: 'kaggle',
  },
  {
    id: '5', slug: 'midjourney', name: 'Midjourney', tagline: 'Generate stunning, artistic images from text',
    description: 'Premium AI image generation known for artistic quality, style consistency, and beautiful aesthetics.',
    website_url: 'https://midjourney.com', logo_url: '',
    category: 'Image Generation', subcategories: ['Design & Creative'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 120,
    use_cases: ['Content Creation', 'Design', 'Marketing'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 7, asia_ready: true, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Creating marketing visuals for Asian tourism, real estate, and hospitality',
    avg_rating: 4.8, total_ratings: 9800, trending_score: 78, saves_count: 15200,
    how_to_use_guide: 'Use descriptive prompts. Reference artists and styles. Use image prompts for consistency.',
    playbook_use_cases: ['Social media visuals', 'Product photography mockups', 'Architecture visualization'],
    playbook_steps: [{ title: 'Craft your prompt', description: 'Describe subject, style, mood, and composition in detail' }, { title: 'Iterate and refine', description: 'Use variations and remix features to dial in the perfect image' }],
    is_published: true, created_at: '2022-07-12', source: 'kaggle',
  },
  {
    id: '6', slug: 'perplexity', name: 'Perplexity', tagline: 'AI-powered research engine with cited answers',
    description: 'Search engine that combines LLM responses with real-time web citations. Perfect for deep research.',
    website_url: 'https://perplexity.ai', logo_url: '',
    category: 'Research & Analysis', subcategories: ['Chatbots & Assistants'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 49,
    use_cases: ['Research', 'Content Creation', 'Productivity'],
    agent_roles: ['Research Assistant', 'Personal Assistant'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web', 'iOS', 'Android'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Market research for Asian markets with cited sources',
    avg_rating: 4.7, total_ratings: 8900, trending_score: 92, saves_count: 22100,
    how_to_use_guide: 'Ask questions like a search engine. Use Collections to organize research. Use Pro for deeper analysis.',
    playbook_use_cases: ['Competitor analysis for Asian markets', 'Travel research', 'Academic research'],
    playbook_steps: [{ title: 'Ask with context', description: 'Add specific context for more relevant results' }, { title: 'Follow sources', description: 'Click citations to verify and dive deeper' }],
    is_published: true, created_at: '2022-12-07', source: 'kaggle',
  },
  {
    id: '7', slug: 'cursor', name: 'Cursor', tagline: 'AI-native code editor built for productivity',
    description: 'VS Code fork with deep AI integration — inline editing, multi-file changes, and agent mode.',
    website_url: 'https://cursor.com', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 40,
    use_cases: ['Code Generation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Desktop'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Accelerating solo devs and small startups across Asia',
    avg_rating: 4.8, total_ratings: 7600, trending_score: 97, saves_count: 28100,
    how_to_use_guide: 'Use Ctrl+K for inline edits. Use Cmd+L for chat. @-mention files for context. Use Agent mode for multi-step tasks.',
    playbook_use_cases: ['Rapid prototyping', 'Full-stack app development', 'Codebase refactoring'],
    playbook_steps: [{ title: 'Open your project', description: 'Cursor understands your entire codebase' }, { title: 'Use Agent mode', description: 'Describe features and Cursor will create/modify multiple files' }],
    is_published: true, created_at: '2023-03-01', source: 'kaggle',
  },
  {
    id: '8', slug: 'notion-ai', name: 'Notion AI', tagline: 'AI-powered workspace for docs, wikis, and projects',
    description: 'Integrated AI assistant inside Notion — write, summarize, brainstorm, and edit without leaving your workspace.',
    website_url: 'https://notion.so', logo_url: '',
    category: 'Productivity', subcategories: ['Writing & Content', 'Business Operations'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 18,
    use_cases: ['Content Creation', 'Productivity', 'Project Management'],
    agent_roles: ['Writing Assistant', 'Project Manager', 'Personal Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'iOS', 'Android', 'Desktop'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Team knowledge management with Asian language support',
    avg_rating: 4.4, total_ratings: 6500, trending_score: 71, saves_count: 12300,
    how_to_use_guide: 'Highlight text for AI actions. Use AI in database views. Create wiki pages from meeting notes.',
    playbook_use_cases: ['Meeting notes summarization', 'Project documentation', 'Team wikis'],
    playbook_steps: [{ title: 'Start writing', description: 'Use AI write to draft documents' }, { title: 'Ask questions', description: 'Query your workspace using Notion AI Q&A' }],
    is_published: true, created_at: '2023-02-22', source: 'kaggle',
  },
  {
    id: '9', slug: 'devin', name: 'Devin', tagline: 'AI software engineer that plans and builds entire apps',
    description: 'Fully autonomous AI coding agent. Describe your app and Devin builds, tests, and deploys it.',
    website_url: 'https://cognition.ai', logo_url: '',
    category: 'AI Agents', subcategories: ['Code & Development'],
    pricing_tier: 'Paid', pricing_min_usd: 500, pricing_max_usd: 500,
    use_cases: ['Code Generation', 'Automation'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Automated web app development for Asian startups',
    avg_rating: 4.3, total_ratings: 3200, trending_score: 85, saves_count: 8900,
    how_to_use_guide: 'Describe your app in natural language. Devin plans the architecture, writes code, and deploys.',
    playbook_use_cases: ['MVP development', 'Rapid prototyping', 'Bug fixing'],
    playbook_steps: [{ title: 'Describe your app', description: 'Write a detailed description of what you want to build' }, { title: 'Review and iterate', description: 'Devin provides a plan — review and approve before execution' }],
    is_published: true, created_at: '2024-03-12', source: 'kaggle',
  },
  {
    id: '10', slug: 'canva-ai', name: 'Canva AI (Magic Studio)', tagline: 'AI-powered design for non-designers',
    description: 'AI design tools integrated into Canva — magic design, text-to-image, AI photo editing, and brand kits.',
    website_url: 'https://canva.com', logo_url: '',
    category: 'Design & Creative', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Freemium', pricing_min_usd: 13, pricing_max_usd: 30,
    use_cases: ['Design', 'Content Creation', 'Marketing'],
    agent_roles: ['Design Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web', 'iOS', 'Android'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Thai', 'Vietnamese', 'Indonesian', 'Hindi'],
    data_residency: 'Global (US, AU)', local_pricing_asia: true, best_for_asia_use_case: 'Asia-local pricing and broadest language support for creators',
    avg_rating: 4.6, total_ratings: 22100, trending_score: 84, saves_count: 18400,
    how_to_use_guide: 'Use Magic Design for instant templates. Magic Eraser for photos. Brand Kit for consistent visuals.',
    playbook_use_cases: ['Social media graphics for Asian markets', 'Presentation decks', 'Marketing collateral'],
    playbook_steps: [{ title: 'Pick a template', description: 'Browse thousands of templates optimized for various platforms' }, { title: 'Customize with AI', description: 'Use Magic Studio tools to generate images, edit photos, and resize designs' }],
    is_published: true, created_at: '2023-10-04', source: 'kaggle',
  },
  {
    id: '11', slug: 'elevenlabs', name: 'ElevenLabs', tagline: 'Most realistic AI voice generation with emotion',
    description: 'Ultra-realistic text-to-speech with voice cloning, emotion control, and multi-language support.',
    website_url: 'https://elevenlabs.io', logo_url: '',
    category: 'Audio & Music', subcategories: ['Video & Animation'],
    pricing_tier: 'Freemium', pricing_min_usd: 5, pricing_max_usd: 330,
    use_cases: ['Audio Production', 'Content Creation', 'Video Production'],
    agent_roles: ['Writing Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'iOS', 'API'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Creating multilingual voiceovers for Asian content creators',
    avg_rating: 4.7, total_ratings: 5400, trending_score: 79, saves_count: 11200,
    how_to_use_guide: 'Choose from hundreds of voices. Adjust stability and clarity. Use voice library or clone your own.',
    playbook_use_cases: ['YouTube voiceovers', 'Audiobook narration', 'Multilingual content'],
    playbook_steps: [{ title: 'Select a voice', description: 'Browse voices or clone one from samples' }, { title: 'Add emotion', description: 'Use stability and clarity sliders for natural delivery' }],
    is_published: true, created_at: '2022-11-08', source: 'kaggle',
  },
  {
    id: '12', slug: 'runway', name: 'Runway', tagline: 'AI video generation and editing platform',
    description: 'Text-to-video, video-to-video, inpainting, and professional editing tools powered by generative AI.',
    website_url: 'https://runwayml.com', logo_url: '',
    category: 'Video & Animation', subcategories: ['Design & Creative'],
    pricing_tier: 'Paid', pricing_min_usd: 12, pricing_max_usd: 76,
    use_cases: ['Video Production', 'Content Creation', 'Design'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'AI video production for marketing teams in Asia',
    avg_rating: 4.5, total_ratings: 6100, trending_score: 76, saves_count: 9800,
    how_to_use_guide: 'Use Gen-3 for text-to-video. Use Video to Video for style transfer. Use Inpainting for edits.',
    playbook_use_cases: ['Marketing videos', 'Product demos', 'Social media content'],
    playbook_steps: [{ title: 'Generate a clip', description: 'Write a detailed prompt for Gen-3 text-to-video' }, { title: 'Edit and refine', description: 'Use inpainting, extend, and frame interpolation' }],
    is_published: true, created_at: '2023-05-18', source: 'kaggle',
  },
  {
    id: '13', slug: 'jasper', name: 'Jasper', tagline: 'AI content platform for marketing teams',
    description: 'Enterprise-grade AI writing platform purpose-built for marketing content, ads, and campaigns.',
    website_url: 'https://jasper.ai', logo_url: '',
    category: 'Writing & Content', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Paid', pricing_min_usd: 49, pricing_max_usd: 499,
    use_cases: ['Content Creation', 'Marketing'],
    agent_roles: ['Writing Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language marketing content for Asian businesses targeting global audiences',
    avg_rating: 4.3, total_ratings: 4200, trending_score: 62, saves_count: 7400,
    how_to_use_guide: 'Use brand voice presets. Start with templates for different content types. Use campaigns for multi-channel content.',
    playbook_use_cases: ['Blog posts', 'Ad copy', 'Email marketing', 'Social media content'],
    playbook_steps: [{ title: 'Choose a template', description: 'Select from 50+ marketing-specific templates' }, { title: 'Customize with brand voice', description: 'Set your brand guidelines for consistent output' }],
    is_published: true, created_at: '2021-01-15', source: 'kaggle',
  },
  {
    id: '14', slug: 'synthesia', name: 'Synthesia', tagline: 'Create AI videos with digital avatars in minutes',
    description: 'Text-to-video platform with realistic AI avatars for corporate training, marketing, and demos.',
    website_url: 'https://synthesia.io', logo_url: '',
    category: 'Video & Animation', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Paid', pricing_min_usd: 29, pricing_max_usd: 89,
    use_cases: ['Video Production', 'Content Creation', 'Marketing'],
    agent_roles: ['Design Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'EU', local_pricing_asia: false, best_for_asia_use_case: 'Asian-language AI avatar videos for training and marketing',
    avg_rating: 4.5, total_ratings: 3800, trending_score: 73, saves_count: 8600,
    how_to_use_guide: 'Choose an avatar. Write your script. Select language and generate. Edit in the timeline.',
    playbook_use_cases: ['Training videos in multiple Asian languages', 'Product demos', 'Personalized sales videos'],
    playbook_steps: [{ title: 'Select avatar', description: 'Choose from 160+ diverse AI avatars' }, { title: 'Write script', description: 'Enter your script and the avatar delivers it naturally' }],
    is_published: true, created_at: '2019-06-01', source: 'kaggle',
  },
  {
    id: '15', slug: 'hugging-face', name: 'Hugging Face', tagline: 'Open platform for AI models and datasets',
    description: 'The largest open-source AI community. Host models, datasets, Spaces demo apps, and collaborate.',
    website_url: 'https://huggingface.co', logo_url: '',
    category: 'Data & Analytics', subcategories: ['Code & Development'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Data Analysis', 'Code Generation', 'Research'],
    agent_roles: ['Code Assistant', 'Data Analyst', 'Research Assistant'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'API'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Free open-source AI models for Asian developers and researchers',
    avg_rating: 4.8, total_ratings: 14200, trending_score: 86, saves_count: 24100,
    how_to_use_guide: 'Browse models by task. Use inference API for quick testing. Deploy Spaces for demos.',
    playbook_use_cases: ['Fine-tuning models for Asian languages', 'Model evaluation', 'AI demos and prototyping'],
    playbook_steps: [{ title: 'Find a model', description: 'Search 200K+ models by task or language' }, { title: 'Test with inference', description: 'Use the hosted inference API before downloading' }],
    is_published: true, created_at: '2016-12-01', source: 'kaggle',
  },
  {
    id: '16', slug: 'langchain', name: 'LangChain', tagline: 'Framework for building LLM-powered applications',
    description: 'Popular open-source framework for chaining LLM calls, building RAG systems, and creating AI agents.',
    website_url: 'https://langchain.com', logo_url: '',
    category: 'No-Code & Automation', subcategories: ['Code & Development'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Code Generation', 'Automation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'N/A (Open Source)', local_pricing_asia: true, best_for_asia_use_case: 'Building custom AI applications with Asian language models',
    avg_rating: 4.6, total_ratings: 8900, trending_score: 90, saves_count: 17200,
    how_to_use_guide: 'Install via pip. Use LangChain Expression Language for chains. Use LangGraph for agents.',
    playbook_use_cases: ['Building RAG systems', 'Creating custom AI agents', 'Multi-model pipelines'],
    playbook_steps: [{ title: 'Install and set up', description: 'pip install langchain langchain-openai' }, { title: 'Create a chain', description: 'Chain together prompts, models, and output parsers' }],
    is_published: true, created_at: '2022-10-01', source: 'kaggle',
  },
  {
    id: '17', slug: 'copy-ai', name: 'Copy.ai', tagline: 'AI-powered go-to-market platform',
    description: 'Content creation and workflow automation for marketing, sales, and revenue teams.',
    website_url: 'https://copy.ai', logo_url: '',
    category: 'Marketing & SEO', subcategories: ['Writing & Content'],
    pricing_tier: 'Freemium', pricing_min_usd: 36, pricing_max_usd: 186,
    use_cases: ['Marketing', 'Content Creation', 'Sales'],
    agent_roles: ['Marketing Agent', 'Sales Agent', 'Writing Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language marketing workflows for Asian B2B companies',
    avg_rating: 4.2, total_ratings: 3100, trending_score: 58, saves_count: 5200,
    how_to_use_guide: 'Use workflows for multi-step content creation. Create branded templates for consistency.',
    playbook_use_cases: ['Email sequences', 'LinkedIn outreach', 'Landing page copy'],
    playbook_steps: [{ title: 'Start a workflow', description: 'Choose from pre-built go-to-market workflows' }, { title: 'Customize output', description: 'Set brand voice, audience, and content goals' }],
    is_published: true, created_at: '2020-10-01', source: 'kaggle',
  },
  {
    id: '18', slug: 'descript', name: 'Descript', tagline: 'AI-powered video and audio editing',
    description: 'Edit video by editing text. AI-powered transcription, voice cloning, screen recording, and collaboration.',
    website_url: 'https://descript.com', logo_url: '',
    category: 'Video & Animation', subcategories: ['Audio & Music', 'Design & Creative'],
    pricing_tier: 'Freemium', pricing_min_usd: 12, pricing_max_usd: 40,
    use_cases: ['Video Production', 'Audio Production', 'Content Creation'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'Desktop'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language video editing for Asian content creators',
    avg_rating: 4.6, total_ratings: 4900, trending_score: 69, saves_count: 9100,
    how_to_use_guide: 'Import video. AI transcribes automatically. Edit text to edit video. Use Studio Sound for audio.',
    playbook_use_cases: ['Podcast editing', 'Tutorial videos', 'Social media clips'],
    playbook_steps: [{ title: 'Import media', description: 'Drag and drop video or audio files' }, { title: 'Edit as text', description: 'Delete words from transcript to remove from video' }],
    is_published: true, created_at: '2017-05-01', source: 'kaggle',
  },
  {
    id: '19', slug: 'murf-ai', name: 'Murf AI', tagline: 'AI voice generator with studio-quality voices',
    description: 'Text-to-speech with 120+ AI voices across 20 languages. Great for e-learning and corporate videos.',
    website_url: 'https://murf.ai', logo_url: '',
    category: 'Audio & Music', subcategories: ['Video & Animation'],
    pricing_tier: 'Paid', pricing_min_usd: 19, pricing_max_usd: 99,
    use_cases: ['Audio Production', 'Video Production', 'Content Creation'],
    agent_roles: ['Writing Assistant', 'Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Asian-language voiceovers for corporate and e-learning',
    avg_rating: 4.4, total_ratings: 2800, trending_score: 55, saves_count: 4200,
    how_to_use_guide: 'Choose voice and language. Enter or paste script. Adjust pitch and speed. Export as MP3/WAV.',
    playbook_use_cases: ['E-learning narration in Asian languages', 'Corporate training videos', 'YouTube voiceovers'],
    playbook_steps: [{ title: 'Select language', description: 'Choose from 20+ languages including Asian languages' }, { title: 'Fine-tune delivery', description: 'Adjust pitch, speed, and emphasis for natural dialogue' }],
    is_published: true, created_at: '2020-08-01', source: 'kaggle',
  },
  {
    id: '20', slug: 'intercom-ai', name: 'Intercom AI (Fin)', tagline: 'AI customer support agent that resolves instantly',
    description: 'AI-powered customer support agent that answers questions, resolves issues, and escalates smartly.',
    website_url: 'https://intercom.com/ai', logo_url: '',
    category: 'Customer Support', subcategories: ['Sales & CRM', 'Chatbots & Assistants'],
    pricing_tier: 'Paid', pricing_min_usd: 39, pricing_max_usd: 139,
    use_cases: ['Customer Support', 'Sales'],
    agent_roles: ['Customer Support Agent', 'Sales Agent'],
    is_agentic: true, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 6, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: '24/7 customer support for Asian e-commerce companies',
    avg_rating: 4.3, total_ratings: 3200, trending_score: 65, saves_count: 5800,
    how_to_use_guide: 'Connect knowledge base. Fin answers from your content. Train with examples for tricky questions.',
    playbook_use_cases: ['E-commerce customer support', 'SaaS product support', 'FAQ automation'],
    playbook_steps: [{ title: 'Connect knowledge base', description: 'Fin reads your help articles to answer questions' }, { title: 'Train your model', description: 'Review and improve answers with custom training' }],
    is_published: true, created_at: '2023-05-01', source: 'kaggle',
  },
];

export default toolsData;
