import { Tool } from './types';

// Seed dataset — 30+ tools covering all major categories
// This simulates the Kaggle dataset import. In production, use Supabase.
export const toolsData: Tool[] = [
  {
    id: '1', slug: 'chatgpt', name: 'ChatGPT', tagline: 'The most versatile AI assistant for daily tasks',
    description: 'Create content, code, research, analyze data, and brainstorm with OpenAI\'s flagship language model.',
    website_url: 'https://chatgpt.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Writing & Content', 'Code & Development', 'Research & Analysis'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 200,
    use_cases: ['Content Creation', 'Code Generation', 'Research', 'Productivity'],
    agent_roles: ['Writing Assistant', 'Code Assistant', 'Research Assistant', 'Personal Assistant'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS', 'Android'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Thai', 'Vietnamese'],
    data_residency: 'Global (US, EU)', local_pricing_asia: false, best_for_asia_use_case: 'Multi-language content creation for Asian markets',
    avg_rating: 4.7, total_ratings: 28450, trending_score: 99, saves_count: 45200,
    how_to_use_guide: 'Start with clear prompts. Use Custom Instructions to set your context. Create GPTs for repeatable workflows.',
    playbook_use_cases: ['Drafting emails in Chinese', 'Translating content across Asian languages', 'Code review', 'Travel itinerary planning'],
    playbook_steps: [{ title: 'Set your context', description: 'Use Custom GPT to define your role, audience, and preferences' }, { title: 'Prompt engineering', description: 'Be specific with tasks, provide examples, iterate on output' }],
    is_published: true, created_at: '2022-11-30', source: 'kaggle',
      solopreneur_score: 10, best_for_smallbusiness_use_case: "All-round AI assistant for solopreneurs", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Vietnamese, Thai, Indonesian", ai_ready: true, community_rating: 4.7, total_community_reviews: 45200, how_to_use_guide_title: "Master ChatGPT for daily workflows", best_for_pipeline_stage: "all-rounder", quick_start_steps: [{step:1,title:"Start a conversation",description:"Open ChatGPT and type your request naturally."},{step:2,title:"Refine with follow-ups",description:"Ask follow-up questions or request revisions."},{step:3,title:"Custom instructions",description:"Set custom instructions in settings."},{step:4,title:"Explore GPTs",description:"Browse the GPT Store for specialised assistants."},{step:5,title:"Use voice and images",description:"Upload images for analysis or use voice mode."}]
  },
  {
    id: '2', slug: 'claude', name: 'Claude', tagline: 'Thoughtful AI for complex reasoning and long documents',
    description: 'Anthropic\'s AI assistant known for nuanced reasoning, safety-first design, and massive context windows.',
    website_url: 'https://claude.ai', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Writing & Content', 'Code & Development', 'Research & Analysis'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 200,
    use_cases: ['Content Creation', 'Code Generation', 'Research', 'Data Analysis'],
    agent_roles: ['Writing Assistant', 'Research Assistant', 'Data Analyst'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Long-form document analysis, contract review in Asia',
    avg_rating: 4.8, total_ratings: 18200, trending_score: 95, saves_count: 32100,
    how_to_use_guide: 'Upload documents up to 200K tokens. Use Projects to organize related work. Ask for step-by-step reasoning.',
    playbook_use_cases: ['Analyzing 100-page contracts', 'Research paper summaries', 'Code architecture review', 'Strategic planning'],
    playbook_steps: [{ title: 'Upload documents', description: 'Claude handles massive context — upload full documents' }, { title: 'Ask for analysis', description: 'Request summaries, comparisons, or deep analysis' }],
    is_published: true, created_at: '2023-03-14', source: 'kaggle',
      solopreneur_score: 9, best_for_smallbusiness_use_case: "Deep analysis and document processing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean", ai_ready: true, community_rating: 4.6, total_community_reviews: 32100, how_to_use_guide_title: "Leverage Claude for deep analysis", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Upload documents",description:"Drag and drop PDFs or Word docs."},{step:2,title:"Ask complex questions",description:"Ask Claude to analyse or extract insights."},{step:3,title:"Use projects",description:"Create Projects with custom instructions."},{step:4,title:"Iterate on outputs",description:"Request revisions with specific feedback."},{step:5,title:"Export and share",description:"Copy outputs, share conversation links."}]
  },
  {
    id: '3', slug: 'gemini', name: 'Gemini', tagline: 'Google\'s multimodal AI with deep search integration',
    description: 'Google\'s most capable AI with native Google ecosystem integration, strong multimodal abilities.',
    website_url: 'https://gemini.google.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Research & Analysis', 'Writing & Content'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Research', 'Content Creation', 'Data Analysis', 'Productivity'],
    agent_roles: ['Research Assistant', 'Personal Assistant', 'Data Analyst'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'iOS', 'Android'],
    asia_score: 10, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi', 'Thai', 'Vietnamese', 'Indonesian'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Best free option for Asian language speakers — supports most Asian languages natively',
    avg_rating: 4.5, total_ratings: 15200, trending_score: 88, saves_count: 28100,
    how_to_use_guide: 'Use deep research mode for complex queries. Leverage Google ecosystem integration for seamless workflows.',
    playbook_use_cases: ['Market research for Asian markets', 'Multi-language translation', 'Google Workspace integration'],
    playbook_steps: [{ title: 'Ask naturally', description: 'Gemini understands conversational queries in many Asian languages' }, { title: 'Use extensions', description: 'Connect to Google Workspace, Maps, Flights for travel planning' }],
    is_published: true, created_at: '2023-12-06', source: 'kaggle',
      solopreneur_score: 8, best_for_smallbusiness_use_case: "Research and long-form content", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Hindi, Thai, Vietnamese", ai_ready: true, community_rating: 4.3, total_community_reviews: 28100, how_to_use_guide_title: "Get the most from Gemini 2.5", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Open Gemini",description:"Start with a simple question."},{step:2,title:"Use Google ecosystem",description:"Connect to Google Workspace."},{step:3,title:"Leverage long context",description:"Paste entire codebases. 1M+ tokens."},{step:4,title:"Deep research",description:"Multi-source document research."},{step:5,title:"Image and video analysis",description:"Upload for native visual analysis."}]
  },
  {
    id: '4', slug: 'copilot', name: 'GitHub Copilot', tagline: 'AI pair programmer that writes code alongside you',
    description: 'Real-time code suggestions in VS Code, JetBrains, and more. The most popular AI coding assistant.',
    website_url: 'https://github.com/features/copilot', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 39,
    use_cases: ['Code Generation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'Desktop'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: 'Accelerating development for Asian tech teams',
    avg_rating: 4.6, total_ratings: 12300, trending_score: 82, saves_count: 19500,
    how_to_use_guide: 'Install in your IDE. Write comments to describe what you want. Tab to accept suggestions.',
    playbook_use_cases: ['Building web apps faster', 'API development', 'Code refactoring'],
    playbook_steps: [{ title: 'Install extension', description: 'Install Copilot in VS Code, JetBrains, or Neovim' }, { title: 'Describe intent', description: 'Write clear comments or function names for best suggestions' }],
    is_published: true, created_at: '2022-06-21', source: 'kaggle',
      solopreneur_score: 8, best_for_smallbusiness_use_case: "Code completion for solo devs", local_language_support: true, supported_languages_detail: "English, Chinese, Japanese", ai_ready: true, community_rating: 4.2, total_community_reviews: 19500, how_to_use_guide_title: "Supercharge your coding with Copilot", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install the extension",description:"Install in VS Code, JetBrains."},{step:2,title:"Start typing",description:"Begin coding. Copilot suggests completions."},{step:3,title:"Write comments",description:"Write a comment describing the code."},{step:4,title:"Use Copilot Chat",description:"Ask about your codebase."},{step:5,title:"Inline fixes",description:"Fix bugs or refactor inline."}]
  },
  {
    id: '5', slug: 'midjourney', name: 'Midjourney', tagline: 'Generate stunning, artistic images from text',
    description: 'Premium AI image generation known for artistic quality, style consistency, and beautiful aesthetics.',
    website_url: 'https://midjourney.com', logo_url: '',
    category: 'Image Generation', subcategories: ['Design & Creative'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 120,
    use_cases: ['Content Creation', 'Design', 'Marketing'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 7, asia_ready: true, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Creating marketing visuals for Asian tourism, real estate, and hospitality',
    avg_rating: 4.8, total_ratings: 9800, trending_score: 78, saves_count: 15200,
    how_to_use_guide: 'Use descriptive prompts. Reference artists and styles. Use image prompts for consistency.',
    playbook_use_cases: ['Social media visuals', 'Product photography mockups', 'Architecture visualization'],
    playbook_steps: [{ title: 'Craft your prompt', description: 'Describe subject, style, mood, and composition in detail' }, { title: 'Iterate and refine', description: 'Use variations and remix features to dial in the perfect image' }],
    is_published: true, created_at: '2022-07-12', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Product photography and branding visuals", local_language_support: false, supported_languages_detail: "English prompts only", ai_ready: false, community_rating: 4.5, total_community_reviews: 15200, how_to_use_guide_title: "Create stunning visuals with Midjourney", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Join Discord",description:"Midjourney runs on Discord."},{step:2,title:"Write your first prompt",description:"Type /imagine with a description."},{step:3,title:"Upscale and vary",description:"U buttons to upscale, V for variations."},{step:4,title:"Refine with parameters",description:"Use --ar, --s parameters."},{step:5,title:"Use Describe feature",description:"Get prompt ideas from images."}]
  },
  {
    id: '6', slug: 'perplexity', name: 'Perplexity', tagline: 'AI-powered research engine with cited answers',
    description: 'Search engine that combines LLM responses with real-time web citations. Perfect for deep research.',
    website_url: 'https://perplexity.ai', logo_url: '',
    category: 'Research & Analysis', subcategories: ['Chatbots & Assistants'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 49,
    use_cases: ['Research', 'Content Creation', 'Productivity'],
    agent_roles: ['Research Assistant', 'Personal Assistant'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web', 'iOS', 'Android'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Market research for Asian markets with cited sources',
    avg_rating: 4.7, total_ratings: 8900, trending_score: 92, saves_count: 22100,
    how_to_use_guide: 'Ask questions like a search engine. Use Collections to organize research. Use Pro for deeper analysis.',
    playbook_use_cases: ['Competitor analysis for Asian markets', 'Travel research', 'Academic research'],
    playbook_steps: [{ title: 'Ask with context', description: 'Add specific context for more relevant results' }, { title: 'Follow sources', description: 'Click citations to verify and dive deeper' }],
    is_published: true, created_at: '2022-12-07', source: 'kaggle',
      solopreneur_score: 9, best_for_smallbusiness_use_case: "Market research and competitor analysis", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.5, total_community_reviews: 22100, how_to_use_guide_title: "Research like a pro with Perplexity", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Ask a research question",description:"Type any question with sources."},{step:2,title:"Choose focus mode",description:"Academic, Writing, Math, Social."},{step:3,title:"Explore follow-ups",description:"Auto-suggested deep-dive questions."},{step:4,title:"Create collections",description:"Save queries for ongoing research."},{step:5,title:"Use Pro search",description:"Multi-step reasoning."}]
  },
  {
    id: '7', slug: 'cursor', name: 'Cursor', tagline: 'AI-native code editor built for productivity',
    description: 'VS Code fork with deep AI integration — inline editing, multi-file changes, and agent mode.',
    website_url: 'https://cursor.com', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents'],
    pricing_tier: 'Freemium', pricing_min_usd: 20, pricing_max_usd: 40,
    use_cases: ['Code Generation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Desktop'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Accelerating solo devs and small startups across Asia',
    avg_rating: 4.8, total_ratings: 7600, trending_score: 97, saves_count: 28100,
    how_to_use_guide: 'Use Ctrl+K for inline edits. Use Cmd+L for chat. @-mention files for context. Use Agent mode for multi-step tasks.',
    playbook_use_cases: ['Rapid prototyping', 'Full-stack app development', 'Codebase refactoring'],
    playbook_steps: [{ title: 'Open your project', description: 'Cursor understands your entire codebase' }, { title: 'Use Agent mode', description: 'Describe features and Cursor will create/modify multiple files' }],
    is_published: true, created_at: '2023-03-01', source: 'kaggle',
      solopreneur_score: 10, best_for_smallbusiness_use_case: "Rapid MVP development for solopreneurs", local_language_support: true, supported_languages_detail: "English, Chinese, Japanese", ai_ready: true, community_rating: 4.8, total_community_reviews: 28100, how_to_use_guide_title: "Build apps faster with Cursor AI", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install Cursor",description:"Download Cursor IDE."},{step:2,title:"Use Composer",description:"Cmd+I for multi-file changes."},{step:3,title:"Chat with codebase",description:"Cmd+L to chat about your project."},{step:4,title:"Agent mode",description:"Autonomous coding with Agent."},{step:5,title:"Cursor rules",description:".cursorrules for preferences."}]
  },
  {
    id: '8', slug: 'notion-ai', name: 'Notion AI', tagline: 'AI-powered workspace for docs, wikis, and projects',
    description: 'Integrated AI assistant inside Notion — write, summarize, brainstorm, and edit without leaving your workspace.',
    website_url: 'https://notion.so', logo_url: '',
    category: 'Productivity', subcategories: ['Writing & Content', 'Business Operations'],
    pricing_tier: 'Paid', pricing_min_usd: 10, pricing_max_usd: 18,
    use_cases: ['Content Creation', 'Productivity', 'Project Management'],
    agent_roles: ['Writing Assistant', 'Project Manager', 'Personal Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'iOS', 'Android', 'Desktop'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Team knowledge management with Asian language support',
    avg_rating: 4.4, total_ratings: 6500, trending_score: 71, saves_count: 12300,
    how_to_use_guide: 'Highlight text for AI actions. Use AI in database views. Create wiki pages from meeting notes.',
    playbook_use_cases: ['Meeting notes summarization', 'Project documentation', 'Team wikis'],
    playbook_steps: [{ title: 'Start writing', description: 'Use AI write to draft documents' }, { title: 'Ask questions', description: 'Query your workspace using Notion AI Q&A' }],
    is_published: true, created_at: '2023-02-22', source: 'kaggle',
      solopreneur_score: 8, best_for_smallbusiness_use_case: "Project management and documentation", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.0, total_community_reviews: 12300, how_to_use_guide_title: "Organise your business with Notion AI", best_for_pipeline_stage: "planning", quick_start_steps: [{step:1,title:"Set up workspace",description:"Create pages for docs and tasks."},{step:2,title:"Use AI features",description:"Cmd+J for Notion AI."},{step:3,title:"Build databases",description:"Task tracking, CRM, calendars."},{step:4,title:"Connect tools",description:"Slack, Drive, Figma integrations."},{step:5,title:"Create templates",description:"Save layouts as templates."}]
  },
  {
    id: '9', slug: 'devin', name: 'Devin', tagline: 'AI software engineer that plans and builds entire apps',
    description: 'Fully autonomous AI coding agent. Describe your app and Devin builds, tests, and deploys it.',
    website_url: 'https://cognition.ai', logo_url: '',
    category: 'AI Agents', subcategories: ['Code & Development'],
    pricing_tier: 'Paid', pricing_min_usd: 500, pricing_max_usd: 500,
    use_cases: ['Code Generation', 'Automation'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Automated web app development for Asian startups',
    avg_rating: 4.3, total_ratings: 3200, trending_score: 85, saves_count: 8900,
    how_to_use_guide: 'Describe your app in natural language. Devin plans the architecture, writes code, and deploys.',
    playbook_use_cases: ['MVP development', 'Rapid prototyping', 'Bug fixing'],
    playbook_steps: [{ title: 'Describe your app', description: 'Write a detailed description of what you want to build' }, { title: 'Review and iterate', description: 'Devin provides a plan — review and approve before execution' }],
    is_published: true, created_at: '2024-03-12', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Autonomous bug fixing and feature dev", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 3.8, total_community_reviews: 8900, how_to_use_guide_title: "Let Devin handle the coding", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Describe your task",description:"Tell Devin in natural language."},{step:2,title:"Watch it work",description:"Devin uses its own tools."},{step:3,title:"Review changes",description:"Full diff with explanation."},{step:4,title:"Provide feedback",description:"Ask for changes."},{step:5,title:"Deploy",description:"Devin handles deployment."}]
  },
  {
    id: '10', slug: 'canva-ai', name: 'Canva AI (Magic Studio)', tagline: 'AI-powered design for non-designers',
    description: 'AI design tools integrated into Canva — magic design, text-to-image, AI photo editing, and brand kits.',
    website_url: 'https://canva.com', logo_url: '',
    category: 'Design & Creative', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Freemium', pricing_min_usd: 13, pricing_max_usd: 30,
    use_cases: ['Design', 'Content Creation', 'Marketing'],
    agent_roles: ['Design Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web', 'iOS', 'Android'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Thai', 'Vietnamese', 'Indonesian', 'Hindi'],
    data_residency: 'Global (US, AU)', local_pricing_asia: true, best_for_asia_use_case: 'Asia-local pricing and broadest language support for creators',
    avg_rating: 4.6, total_ratings: 22100, trending_score: 84, saves_count: 18400,
    how_to_use_guide: 'Use Magic Design for instant templates. Magic Eraser for photos. Brand Kit for consistent visuals.',
    playbook_use_cases: ['Social media graphics for Asian markets', 'Presentation decks', 'Marketing collateral'],
    playbook_steps: [{ title: 'Pick a template', description: 'Browse thousands of templates optimized for various platforms' }, { title: 'Customize with AI', description: 'Use Magic Studio tools to generate images, edit photos, and resize designs' }],
    is_published: true, created_at: '2023-10-04', source: 'kaggle',
      solopreneur_score: 9, best_for_smallbusiness_use_case: "Social media graphics and presentations", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Thai, Vietnamese, English", ai_ready: true, community_rating: 4.4, total_community_reviews: 18400, how_to_use_guide_title: "Design everything with Canva AI", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Create a design",description:"Template or Magic Design."},{step:2,title:"Use Magic Studio",description:"Write, Eraser, Animator."},{step:3,title:"Brand kit",description:"Upload logos and colours."},{step:4,title:"Collaborate",description:"Real-time collaboration."},{step:5,title:"Export",description:"Export or schedule social posts."}]
  },
  {
    id: '11', slug: 'elevenlabs', name: 'ElevenLabs', tagline: 'Most realistic AI voice generation with emotion',
    description: 'Ultra-realistic text-to-speech with voice cloning, emotion control, and multi-language support.',
    website_url: 'https://elevenlabs.io', logo_url: '',
    category: 'Audio & Music', subcategories: ['Video & Animation'],
    pricing_tier: 'Freemium', pricing_min_usd: 5, pricing_max_usd: 330,
    use_cases: ['Audio Production', 'Content Creation', 'Video Production'],
    agent_roles: ['Writing Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'iOS', 'API'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Creating multilingual voiceovers for Asian content creators',
    avg_rating: 4.7, total_ratings: 5400, trending_score: 79, saves_count: 11200,
    how_to_use_guide: 'Choose from hundreds of voices. Adjust stability and clarity. Use voice library or clone your own.',
    playbook_use_cases: ['YouTube voiceovers', 'Audiobook narration', 'Multilingual content'],
    playbook_steps: [{ title: 'Select a voice', description: 'Browse voices or clone one from samples' }, { title: 'Add emotion', description: 'Use stability and clarity sliders for natural delivery' }],
    is_published: true, created_at: '2022-11-08', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Marketing copy and blog content", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.2, total_community_reviews: 4200, how_to_use_guide_title: "Generate marketing content at scale", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Choose a template",description:"50+ templates."},{step:2,title:"Set brand voice",description:"Define tone and audience."},{step:3,title:"Generate and refine",description:"Multiple versions to choose from."}]
  },
  {
    id: '12', slug: 'runway', name: 'Runway', tagline: 'AI video generation and editing platform',
    description: 'Text-to-video, video-to-video, inpainting, and professional editing tools powered by generative AI.',
    website_url: 'https://runwayml.com', logo_url: '',
    category: 'Video & Animation', subcategories: ['Design & Creative'],
    pricing_tier: 'Paid', pricing_min_usd: 12, pricing_max_usd: 76,
    use_cases: ['Video Production', 'Content Creation', 'Design'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: true, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'AI video production for marketing teams in Asia',
    avg_rating: 4.5, total_ratings: 6100, trending_score: 76, saves_count: 9800,
    how_to_use_guide: 'Use Gen-3 for text-to-video. Use Video to Video for style transfer. Use Inpainting for edits.',
    playbook_use_cases: ['Marketing videos', 'Product demos', 'Social media content'],
    playbook_steps: [{ title: 'Generate a clip', description: 'Write a detailed prompt for Gen-3 text-to-video' }, { title: 'Edit and refine', description: 'Use inpainting, extend, and frame interpolation' }],
    is_published: true, created_at: '2023-05-18', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Business writing and email polish", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.3, total_community_reviews: 3800, how_to_use_guide_title: "Write better with Grammarly AI", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Install everywhere",description:"Browser, desktop, mobile."},{step:2,title:"Write confidently",description:"Real-time tone and grammar checks."},{step:3,title:"Set goals",description:"Set tone, audience, formality."}]
  },
  {
    id: '13', slug: 'jasper', name: 'Jasper', tagline: 'AI content platform for marketing teams',
    description: 'Enterprise-grade AI writing platform purpose-built for marketing content, ads, and campaigns.',
    website_url: 'https://jasper.ai', logo_url: '',
    category: 'Writing & Content', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Paid', pricing_min_usd: 49, pricing_max_usd: 499,
    use_cases: ['Content Creation', 'Marketing'],
    agent_roles: ['Writing Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language marketing content for Asian businesses targeting global audiences',
    avg_rating: 4.3, total_ratings: 4200, trending_score: 62, saves_count: 7400,
    how_to_use_guide: 'Use brand voice presets. Start with templates for different content types. Use campaigns for multi-channel content.',
    playbook_use_cases: ['Blog posts', 'Ad copy', 'Email marketing', 'Social media content'],
    playbook_steps: [{ title: 'Choose a template', description: 'Select from 50+ marketing-specific templates' }, { title: 'Customize with brand voice', description: 'Set your brand guidelines for consistent output' }],
    is_published: true, created_at: '2021-01-15', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Marketing content and copywriting", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.2, total_community_reviews: 4200, how_to_use_guide_title: "Generate marketing content at scale", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Start with a workflow",description:"Blog, social, email."},{step:2,title:"Enter details",description:"Topic, keywords, voice."},{step:3,title:"Use Infobase",description:"Brand guidelines for consistency."}]
  },
  {
    id: '14', slug: 'synthesia', name: 'Synthesia', tagline: 'Create AI videos with digital avatars in minutes',
    description: 'Text-to-video platform with realistic AI avatars for corporate training, marketing, and demos.',
    website_url: 'https://synthesia.io', logo_url: '',
    category: 'Video & Animation', subcategories: ['Marketing & SEO'],
    pricing_tier: 'Paid', pricing_min_usd: 29, pricing_max_usd: 89,
    use_cases: ['Video Production', 'Content Creation', 'Marketing'],
    agent_roles: ['Design Assistant', 'Marketing Agent'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'EU', local_pricing_asia: false, best_for_asia_use_case: 'Asian-language AI avatar videos for training and marketing',
    avg_rating: 4.5, total_ratings: 3800, trending_score: 73, saves_count: 8600,
    how_to_use_guide: 'Choose an avatar. Write your script. Select language and generate. Edit in the timeline.',
    playbook_use_cases: ['Training videos in multiple Asian languages', 'Product demos', 'Personalized sales videos'],
    playbook_steps: [{ title: 'Select avatar', description: 'Choose from 160+ diverse AI avatars' }, { title: 'Write script', description: 'Enter your script and the avatar delivers it naturally' }],
    is_published: true, created_at: '2019-06-01', source: 'kaggle',
      solopreneur_score: 6, best_for_smallbusiness_use_case: "AI video content for marketing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English, Spanish", ai_ready: false, community_rating: 4.1, total_community_reviews: 5100, how_to_use_guide_title: "Create AI videos in minutes", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Choose an avatar",description:"160+ avatars."},{step:2,title:"Write your script",description:"Converts to speech."},{step:3,title:"Customise video",description:"Add backgrounds and music."}]
  },
  {
    id: '15', slug: 'hugging-face', name: 'Hugging Face', tagline: 'Open platform for AI models and datasets',
    description: 'The largest open-source AI community. Host models, datasets, Spaces demo apps, and collaborate.',
    website_url: 'https://huggingface.co', logo_url: '',
    category: 'Data & Analytics', subcategories: ['Code & Development'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Data Analysis', 'Code Generation', 'Research'],
    agent_roles: ['Code Assistant', 'Data Analyst', 'Research Assistant'],
    is_agentic: false, is_multimodal: true, has_api: true, platform: ['Web', 'API'],
    asia_score: 9, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'Global', local_pricing_asia: true, best_for_asia_use_case: 'Free open-source AI models for Asian developers and researchers',
    avg_rating: 4.8, total_ratings: 14200, trending_score: 86, saves_count: 24100,
    how_to_use_guide: 'Browse models by task. Use inference API for quick testing. Deploy Spaces for demos.',
    playbook_use_cases: ['Fine-tuning models for Asian languages', 'Model evaluation', 'AI demos and prototyping'],
    playbook_steps: [{ title: 'Find a model', description: 'Search 200K+ models by task or language' }, { title: 'Test with inference', description: 'Use the hosted inference API before downloading' }],
    is_published: true, created_at: '2016-12-01', source: 'kaggle',
      solopreneur_score: 5, best_for_smallbusiness_use_case: "Custom AI model hosting", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: false, community_rating: 4.6, total_community_reviews: 24100, how_to_use_guide_title: "Explore and deploy open-source AI", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Explore the Hub",description:"500K+ models."},{step:2,title:"Use Spaces",description:"Interactive demos."},{step:3,title:"Deploy with API",description:"Free Inference API."}]
  },
  {
    id: '16', slug: 'langchain', name: 'LangChain', tagline: 'Framework for building LLM-powered applications',
    description: 'Popular open-source framework for chaining LLM calls, building RAG systems, and creating AI agents.',
    website_url: 'https://langchain.com', logo_url: '',
    category: 'No-Code & Automation', subcategories: ['Code & Development'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: 0,
    use_cases: ['Code Generation', 'Automation', 'Productivity'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 8, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean'],
    data_residency: 'N/A (Open Source)', local_pricing_asia: true, best_for_asia_use_case: 'Building custom AI applications with Asian language models',
    avg_rating: 4.6, total_ratings: 8900, trending_score: 90, saves_count: 17200,
    how_to_use_guide: 'Install via pip. Use LangChain Expression Language for chains. Use LangGraph for agents.',
    playbook_use_cases: ['Building RAG systems', 'Creating custom AI agents', 'Multi-model pipelines'],
    playbook_steps: [{ title: 'Install and set up', description: 'pip install langchain langchain-openai' }, { title: 'Create a chain', description: 'Chain together prompts, models, and output parsers' }],
    is_published: true, created_at: '2022-10-01', source: 'kaggle',
      solopreneur_score: 6, best_for_smallbusiness_use_case: "Building custom AI workflows", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: false, community_rating: 4.3, total_community_reviews: 17200, how_to_use_guide_title: "Build LLM applications", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install LangChain",description:"pip install langchain."},{step:2,title:"Set up LLM",description:"Configure with API key."},{step:3,title:"Build a chain",description:"Prompt + LLM + parser."}]
  },
  {
    id: '17', slug: 'copy-ai', name: 'Copy.ai', tagline: 'AI-powered go-to-market platform',
    description: 'Content creation and workflow automation for marketing, sales, and revenue teams.',
    website_url: 'https://copy.ai', logo_url: '',
    category: 'Marketing & SEO', subcategories: ['Writing & Content'],
    pricing_tier: 'Freemium', pricing_min_usd: 36, pricing_max_usd: 186,
    use_cases: ['Marketing', 'Content Creation', 'Sales'],
    agent_roles: ['Marketing Agent', 'Sales Agent', 'Writing Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language marketing workflows for Asian B2B companies',
    avg_rating: 4.2, total_ratings: 3100, trending_score: 58, saves_count: 5200,
    how_to_use_guide: 'Use workflows for multi-step content creation. Create branded templates for consistency.',
    playbook_use_cases: ['Email sequences', 'LinkedIn outreach', 'Landing page copy'],
    playbook_steps: [{ title: 'Start a workflow', description: 'Choose from pre-built go-to-market workflows' }, { title: 'Customize output', description: 'Set brand voice, audience, and content goals' }],
    is_published: true, created_at: '2020-10-01', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Voiceovers for content and ads", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.4, total_community_reviews: 9800, how_to_use_guide_title: "Generate professional voiceovers", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Choose a voice",description:"1000+ options."},{step:2,title:"Type or upload",description:"Converts to natural speech."},{step:3,title:"Voice Design",description:"Custom age, gender, accent."}]
  },
  {
    id: '18', slug: 'descript', name: 'Descript', tagline: 'AI-powered video and audio editing',
    description: 'Edit video by editing text. AI-powered transcription, voice cloning, screen recording, and collaboration.',
    website_url: 'https://descript.com', logo_url: '',
    category: 'Video & Animation', subcategories: ['Audio & Music', 'Design & Creative'],
    pricing_tier: 'Freemium', pricing_min_usd: 12, pricing_max_usd: 40,
    use_cases: ['Video Production', 'Audio Production', 'Content Creation'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'Desktop'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'English-language video editing for Asian content creators',
    avg_rating: 4.6, total_ratings: 4900, trending_score: 69, saves_count: 9100,
    how_to_use_guide: 'Import video. AI transcribes automatically. Edit text to edit video. Use Studio Sound for audio.',
    playbook_use_cases: ['Podcast editing', 'Tutorial videos', 'Social media clips'],
    playbook_steps: [{ title: 'Import media', description: 'Drag and drop video or audio files' }, { title: 'Edit as text', description: 'Delete words from transcript to remove from video' }],
    is_published: true, created_at: '2017-05-01', source: 'kaggle',
      solopreneur_score: 6, best_for_smallbusiness_use_case: "Video editing and generation", local_language_support: false, supported_languages_detail: "English only", ai_ready: false, community_rating: 4.2, total_community_reviews: 7400, how_to_use_guide_title: "Edit video with AI tools", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Choose a tool",description:"Text-to-Video, Inpainting."},{step:2,title:"Write your prompt",description:"Describe the video."},{step:3,title:"Edit timeline",description:"Transitions and timing."}]
  },
  {
    id: '19', slug: 'murf-ai', name: 'Murf AI', tagline: 'AI voice generator with studio-quality voices',
    description: 'Text-to-speech with 120+ AI voices across 20 languages. Great for e-learning and corporate videos.',
    website_url: 'https://murf.ai', logo_url: '',
    category: 'Audio & Music', subcategories: ['Video & Animation'],
    pricing_tier: 'Paid', pricing_min_usd: 19, pricing_max_usd: 99,
    use_cases: ['Audio Production', 'Video Production', 'Content Creation'],
    agent_roles: ['Writing Assistant', 'Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 7, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese', 'Korean', 'Hindi'],
    data_residency: 'US', local_pricing_asia: false, best_for_asia_use_case: 'Asian-language voiceovers for corporate and e-learning',
    avg_rating: 4.4, total_ratings: 2800, trending_score: 55, saves_count: 4200,
    how_to_use_guide: 'Choose voice and language. Enter or paste script. Adjust pitch and speed. Export as MP3/WAV.',
    playbook_use_cases: ['E-learning narration in Asian languages', 'Corporate training videos', 'YouTube voiceovers'],
    playbook_steps: [{ title: 'Select language', description: 'Choose from 20+ languages including Asian languages' }, { title: 'Fine-tune delivery', description: 'Adjust pitch, speed, and emphasis for natural dialogue' }],
    is_published: true, created_at: '2020-08-01', source: 'kaggle',
      solopreneur_score: 7, best_for_smallbusiness_use_case: "Podcast and video editing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.3, total_community_reviews: 6100, how_to_use_guide_title: "Edit audio and video as text", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Import media",description:"AI transcribes instantly."},{step:2,title:"Edit as text",description:"Delete or rearrange words."},{step:3,title:"Studio Sound",description:"Remove noise, enhance voice."}]
  },
  {
    id: '20', slug: 'intercom-ai', name: 'Intercom AI (Fin)', tagline: 'AI customer support agent that resolves instantly',
    description: 'AI-powered customer support agent that answers questions, resolves issues, and escalates smartly.',
    website_url: 'https://intercom.com/ai', logo_url: '',
    category: 'Customer Support', subcategories: ['Sales & CRM', 'Chatbots & Assistants'],
    pricing_tier: 'Paid', pricing_min_usd: 39, pricing_max_usd: 139,
    use_cases: ['Customer Support', 'Sales'],
    agent_roles: ['Customer Support Agent', 'Sales Agent'],
    is_agentic: true, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 6, asia_ready: true, supports_languages: ['English', 'Chinese', 'Japanese'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: '24/7 customer support for Asian e-commerce companies',
    avg_rating: 4.3, total_ratings: 3200, trending_score: 65, saves_count: 5800,
    how_to_use_guide: 'Connect knowledge base. Fin answers from your content. Train with examples for tricky questions.',
    playbook_use_cases: ['E-commerce customer support', 'SaaS product support', 'FAQ automation'],
    playbook_steps: [{ title: 'Connect knowledge base', description: 'Fin reads your help articles to answer questions' }, { title: 'Train your model', description: 'Review and improve answers with custom training' }],
    is_published: true, created_at: '2023-05-01', source: 'kaggle',
      solopreneur_score: 6, best_for_smallbusiness_use_case: "Customer support automation", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.3, total_community_reviews: 3200, how_to_use_guide_title: "Automate support with Fin", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Connect knowledge base",description:"Fin reads your help articles."},{step:2,title:"Set up Fin",description:"Configure tone and personality."},{step:3,title:"Train with examples",description:"Handle tricky questions."}]
  },
{
    id: '21', slug: 'deepl', name: 'DeepL', tagline: 'AI-powered translation for businesses',
    description: 'Context-aware neural machine translation supporting 31 languages with formal/informal tone options.',
    long_description: 'DeepL is widely considered the most accurate machine translation tool, especially for European and Asian language pairs. Pro plan offers unlimited text translation, document translation, and custom glossaries for enterprise terminology. Uses specialised neural networks trained on high-quality linguistic data.',
    website_url: 'https://deepl.com', logo_url: '',
    category: 'Productivity', subcategories: ['Research & Analysis', 'Business Operations'],
    pricing_tier: 'Freemium', pricing_min_usd: 8.99, pricing_max_usd: 49.99,
    use_cases: ['Translation', 'Content Creation', 'Research'],
    agent_roles: ['Writing Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'Desktop', 'Mobile', 'Browser Extension'],
    asia_score: 6, asia_ready: true, supports_languages: ['Chinese', 'Japanese', 'Korean', 'English', 'French', 'German', 'Spanish'],
    data_residency: 'Europe (GDPR)', local_pricing_asia: true, best_for_asia_use_case: 'Accurate Chinese-to-English business translation with formal tone options',
    avg_rating: 4.5, total_ratings: 8900, trending_score: 55, saves_count: 9200,
    how_to_use_guide: 'DeepL supports text translation up to 5000 chars in free tier. Use DeepL Write for grammar and style improvements. Pro users get unlimited translation and custom glossaries.',
    playbook_use_cases: ['Content translation', 'Business documents', 'Website localization', 'Email translation'],
    playbook_steps: [{title: 'Paste or type text', description: 'Paste text directly or use the browser extension for instant translation'}, {title: 'Select language pair', description: 'Choose from 31 languages. DeepL detects the source language automatically.'}],
    solopreneur_score: 7, best_for_smallbusiness_use_case: 'Multilingual content and business translation', local_language_support: true, supported_languages_detail: 'Chinese, Japanese, Korean, English, major European', ai_ready: true,
    community_rating: 4.5, total_community_reviews: 8900, how_to_use_guide_title: 'Translate accurately with DeepL', best_for_pipeline_stage: 'content',
    quick_start_steps: [{step: 1, title: 'Paste your text', description: 'Copy and paste text into DeepL or use the browser extension for one-click translation.'}, {step: 2, title: 'Choose your tone', description: 'DeepL offers formal and informal tone options.'}, {step: 3, title: 'Use glossary', description: 'Create custom glossaries for business terminology to keep translations consistent.'}],
    is_published: true, created_at: '2022-03-15', source: 'enriched',
  },
  {
    id: '22', slug: 'deepseek', name: 'DeepSeek Chat', tagline: 'Open-weight LLM with strong reasoning',
    description: 'DeepSeek flagship chat model with exceptional reasoning, coding, and mathematics. Open weights enable community fine-tuning.',
    long_description: 'DeepSeek Chat (DeepSeek-V3/R1) has massive popularity for strong reasoning and coding. Generous free tier, 128K context, competitive with GPT-4 on benchmarks. Particularly strong in Chinese language tasks. Popular among Chinese-speaking developers and researchers. Open-weight access for local deployment.',
    website_url: 'https://chat.deepseek.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Code & Development', 'Research & Analysis'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: null,
    use_cases: ['Code Generation', 'Research', 'Data Analysis', 'Writing'],
    agent_roles: ['Code Assistant', 'Research Assistant', 'Writing Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'Mobile', 'API'],
    asia_score: 9, asia_ready: true, supports_languages: ['Chinese', 'English'],
    data_residency: 'China / Global', local_pricing_asia: true, best_for_asia_use_case: 'Best Chinese-language AI assistant with strong coding abilities',
    avg_rating: 4.6, total_ratings: 12500, trending_score: 98, saves_count: 18500,
    how_to_use_guide: 'Free tier includes access to DeepSeek-R1 reasoning model. Upload files (PDF, Word, Excel, PPT, images) for analysis. Supports web search toggle. 128K context window.',
    playbook_use_cases: ['Chinese content creation', 'Code generation', 'Data analysis', 'Long context research'],
    playbook_steps: [{title: 'Start chatting', description: 'No signup needed for basic use. Create account for conversation history and file upload.'}],
    solopreneur_score: 9, best_for_smallbusiness_use_case: 'Free powerful LLM for Chinese-language businesses', local_language_support: true, supported_languages_detail: 'Chinese (simplified + traditional), English', ai_ready: true,
    community_rating: 4.6, total_community_reviews: 12500, how_to_use_guide_title: 'Get started with DeepSeek Chat', best_for_pipeline_stage: 'coding',
    quick_start_steps: [{step: 1, title: 'Start a conversation', description: 'Ask anything in Chinese or English. Excels at reasoning and math.'}, {step: 2, title: 'Upload files', description: 'Upload PDF, Word, Excel, or images for analysis.'}, {step: 3, title: 'Enable web search', description: 'Toggle web search manually for real-time information.'}],
    is_published: true, created_at: '2024-06-01', source: 'enriched',
  },
  {
    id: '23', slug: 'qwen', name: 'Qwen (Tongyi Qianwen)', tagline: "Alibaba's comprehensive AI model family",
    description: "Alibaba Cloud's LLM family covering text, code, image, audio, and video. Strong multilingual with emphasis on Asian languages.",
    long_description: 'Qwen (Tongyi Qianwen) is Alibaba Cloud flagship AI model series. Qwen2.5 family covers 0.5B to 72B+ parameters. Qwen2.5-VL excels at visual understanding, Qwen2.5-Coder is strong for programming, Qwen2-Audio handles speech. Supports 29+ languages with particularly strong Chinese, Japanese, Korean, Vietnamese.',
    website_url: 'https://tongyi.aliyun.com', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['AI Agents', 'Code & Development', 'Audio & Music'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: null,
    use_cases: ['Code Generation', 'Content Creation', 'Data Analysis', 'Image Understanding'],
    agent_roles: ['Code Assistant', 'Research Assistant', 'Personal Assistant'],
    is_agentic: true, is_multimodal: true, has_api: true, platform: ['Web', 'Mobile', 'API', 'Alibaba Cloud'],
    asia_score: 10, asia_ready: true, supports_languages: ['Chinese', 'English', 'Japanese', 'Korean', 'Vietnamese', 'Thai', 'Indonesian'],
    data_residency: 'China, Singapore, Global', local_pricing_asia: true, best_for_asia_use_case: 'Best AI for multilingual Asian business operations',
    avg_rating: 4.2, total_ratings: 6800, trending_score: 88, saves_count: 11000,
    how_to_use_guide: 'Access via tongyi.aliyun.com for free web chat. Developers can use Alibaba Cloud API with competitive pricing. Also available on Hugging Face for local deployment.',
    playbook_use_cases: ['Multilingual customer support', 'Chinese content generation', 'Visual analysis', 'Voice applications'],
    playbook_steps: [{title: 'Access Qwen', description: 'Visit tongyi.aliyun.com or use Alibaba Cloud API for programmatic access.'}],
    solopreneur_score: 7, best_for_smallbusiness_use_case: 'Free multilingual AI for Asian market businesses', local_language_support: true, supported_languages_detail: 'Chinese, English, Japanese, Korean, Vietnamese, Thai, Indonesian', ai_ready: true,
    community_rating: 4.2, total_community_reviews: 6800, how_to_use_guide_title: 'Use Alibaba Qwen AI', best_for_pipeline_stage: 'all-rounder',
    quick_start_steps: [{step: 1, title: 'Start on the web', description: 'Visit tongyi.aliyun.com. Free chat in Chinese or English.'}, {step: 2, title: 'Upload images', description: 'Qwen2.5-VL reads text from images and analyses diagrams.'}, {step: 3, title: 'Use API', description: 'Alibaba Cloud API for integrating into your applications.'}],
    is_published: true, created_at: '2024-01-15', source: 'enriched',
  },
  {
    id: '24', slug: 'kimi', name: 'Kimi', tagline: 'Long-context AI assistant by Moonshot AI',
    description: 'Chinese AI assistant known for 200K+ token context. Excels at processing long documents, research papers, and code repos.',
    long_description: 'Kimi by Moonshot AI stands out for its 200K+ token context window in a single conversation. Excels at summarising long PDFs, analysing code repositories, and multi-source research. Strong Chinese capabilities. Widely used by Chinese researchers, developers, and students for document analysis.',
    website_url: 'https://kimi.moonshot.cn', logo_url: '',
    category: 'Chatbots & Assistants', subcategories: ['Research & Analysis', 'Productivity'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: null,
    use_cases: ['Document Analysis', 'Research', 'Content Writing', 'Code Review'],
    agent_roles: ['Research Assistant', 'Writing Assistant', 'Code Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web', 'Mobile'],
    asia_score: 9, asia_ready: true, supports_languages: ['Chinese', 'English'],
    data_residency: 'China', local_pricing_asia: true, best_for_asia_use_case: 'Best for Chinese-language document analysis and long-form research',
    avg_rating: 4.4, total_ratings: 5100, trending_score: 75, saves_count: 7800,
    how_to_use_guide: 'Upload PDFs, Word docs, or text files up to 200K tokens. Kimi summarises, answers questions, and extracts key information. Great for research paper analysis and contract review.',
    playbook_use_cases: ['Research paper analysis', 'Contract review', 'Code documentation analysis', 'Long-form content summarisation'],
    playbook_steps: [{title: 'Upload document', description: 'Drag and drop PDFs or text files. Kimi reads and indexes the content.'}, {title: 'Ask questions', description: 'Ask specific questions about the document content. Kimi cites relevant sections.'}],
    solopreneur_score: 6, best_for_smallbusiness_use_case: 'Document analysis for Chinese market research', local_language_support: true, supported_languages_detail: 'Chinese, English', ai_ready: true,
    community_rating: 4.4, total_community_reviews: 5100, how_to_use_guide_title: 'Analyse long documents with Kimi', best_for_pipeline_stage: 'research',
    quick_start_steps: [{step: 1, title: 'Upload a document', description: 'Drag PDFs, Word docs, or text files into Kimi for instant processing.'}, {step: 2, title: 'Ask questions', description: 'Ask specific questions. Kimi cites relevant sections from your documents.'}, {step: 3, title: 'Compare documents', description: 'Upload multiple documents and ask Kimi to compare or cross-reference them.'}],
    is_published: true, created_at: '2024-03-01', source: 'enriched',
  },
  {
    id: '25', slug: 'leonardo-ai', name: 'Leonardo AI', tagline: 'AI image generation with advanced controls',
    description: 'Platform for generating production-quality images, game assets, and concept art with fine-grained style controls.',
    long_description: 'Leonardo AI is a powerful image generation platform with features like real-time generation, canvas editor, refiner, and model training. It offers pre-trained community models, custom model training, and image-to-image capabilities. Popular among game developers, graphic designers, and content creators for its quality and control. Free tier includes 150 daily credits.',
    website_url: 'https://leonardo.ai', logo_url: '',
    category: 'Image Generation', subcategories: ['Design & Creative', 'Video & Animation'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: 48,
    use_cases: ['Image Generation', 'Design', 'Game Asset Creation', 'Concept Art'],
    agent_roles: ['Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: true, platform: ['Web', 'API'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: 'Product and marketing visual content for Asian e-commerce',
    avg_rating: 4.4, total_ratings: 7800, trending_score: 72, saves_count: 10500,
    how_to_use_guide: 'Start with pre-trained community models. Use the canvas editor for inpainting and outpainting. Train custom models with your own images for consistent style.',
    playbook_use_cases: ['Product images', 'Game assets', 'Concept art', 'Marketing visuals'],
    playbook_steps: [{title: 'Choose a model', description: 'Select from pre-trained community models or train your own.'}, {title: 'Write your prompt', description: 'Describe what you want in detail. Use negative prompts to avoid unwanted elements.'}],
    solopreneur_score: 7, best_for_smallbusiness_use_case: 'Product visuals and marketing images', local_language_support: false, supported_languages_detail: 'English only', ai_ready: false,
    community_rating: 4.4, total_community_reviews: 7800, how_to_use_guide_title: 'Generate production visuals with Leonardo', best_for_pipeline_stage: 'design',
    quick_start_steps: [{step: 1, title: 'Choose a model', description: 'Pick from community models for different styles.'}, {step: 2, title: 'Generate images', description: 'Write detailed prompts. Use negative prompts to control output.'}, {step: 3, title: 'Enhance with tools', description: 'Use canvas editor, refiner, and image-to-image for fine control.'}],
    is_published: true, created_at: '2023-06-01', source: 'enriched',
  },
  {
    id: '26', slug: 'bolt-new', name: 'Bolt.new', tagline: 'Full-stack web apps from a single prompt',
    description: 'AI-powered full-stack web app builder. Describe your app and Bolt.new generates, runs, and deploys it in-browser.',
    long_description: 'Bolt.new by StackBlitz is a revolutionary tool that lets you build full-stack web applications from a single prompt. It creates a running app with frontend, backend, database, and API routes in one go. Supports Next.js, React, Vue, Svelte, and multiple backend frameworks. Features in-browser code editor, real-time preview, and one-click deploy to Netlify. Hugely popular among solopreneurs for rapid prototyping.',
    website_url: 'https://bolt.new', logo_url: '',
    category: 'Code & Development', subcategories: ['No-Code & Automation', 'AI Agents'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: 50,
    use_cases: ['Code Generation', 'Prototyping', 'Full-Stack Apps', 'MVP Development'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global (US)', local_pricing_asia: false, best_for_asia_use_case: 'Rapid MVP prototyping for Asian startup founders',
    avg_rating: 4.3, total_ratings: 6200, trending_score: 95, saves_count: 15800,
    how_to_use_guide: 'Describe your app in natural language. Bolt.new generates the full stack. Edit in-browser and deploy with one click. Free tier includes limited tokens.',
    playbook_use_cases: ['Rapid prototyping', 'MVP development', 'Full-stack apps', 'API testing'],
    playbook_steps: [{title: 'Describe your app', description: 'Write a detailed description of what you want to build.'}, {title: 'Review the output', description: 'Bolt.new generates a full-stack app with real-time preview.'}],
    solopreneur_score: 9, best_for_smallbusiness_use_case: 'Rapid MVP building for solopreneurs', local_language_support: false, supported_languages_detail: 'English only', ai_ready: true,
    community_rating: 4.3, total_community_reviews: 6200, how_to_use_guide_title: 'Build full-stack apps from a prompt', best_for_pipeline_stage: 'coding',
    quick_start_steps: [{step: 1, title: 'Describe your app', description: 'Write a detailed prompt like "Build a todo app with Next.js and a Postgres DB."'}, {step: 2, title: 'Customise in browser', description: 'Edit the generated code in the built-in editor with real-time preview.'}, {step: 3, title: 'Deploy instantly', description: 'One-click deploy to Netlify or download the code.'}],
    is_published: true, created_at: '2025-01-15', source: 'enriched',
  },
  {
    id: '27', slug: 'lovable', name: 'Lovable', tagline: 'AI app builder for non-technical founders',
    description: 'Platform that lets you build quality web applications by describing your vision. No coding required to get started.',
    long_description: 'Lovable is designed for non-technical users who want to build real web applications. It uses AI to scaffold full applications based on natural language descriptions. Features includes visual editing, database integration, authentication, and deployment. Particularly strong for CRUD apps, dashboards, and internal tools. Popular among founders who want to build MVPs without hiring developers.',
    website_url: 'https://lovable.dev', logo_url: '',
    category: 'No-Code & Automation', subcategories: ['Code & Development', 'Productivity'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: 100,
    use_cases: ['Code Generation', 'Prototyping', 'MVP Development', 'Internal Tools'],
    agent_roles: ['Code Assistant', 'Personal Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 5, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global (EU)', local_pricing_asia: false, best_for_asia_use_case: 'MVP creation for non-technical founders in Asia',
    avg_rating: 4.2, total_ratings: 4800, trending_score: 82, saves_count: 12000,
    how_to_use_guide: 'Describe your app idea. Lovable builds the UI, logic, and database. Use the visual editor to tweak layouts. Deploy with one click.',
    playbook_use_cases: ['MVP creation', 'Internal dashboards', 'CRUD apps', 'Data management tools'],
    playbook_steps: [{title: 'Describe your idea', description: 'Tell Lovable what you want to build in plain language.'}, {title: 'Edit visually', description: 'Use the drag-and-drop editor to tweak app layout and design.'}],
    solopreneur_score: 8, best_for_smallbusiness_use_case: 'Build MVPs without coding', local_language_support: false, supported_languages_detail: 'English only', ai_ready: true,
    community_rating: 4.2, total_community_reviews: 4800, how_to_use_guide_title: 'Build apps without code with Lovable', best_for_pipeline_stage: 'coding',
    quick_start_steps: [{step: 1, title: 'Describe your app', description: 'Write what you want to build in plain English.'}, {step: 2, title: 'Customise visually', description: 'Use the drag-and-drop editor to refine your app layout.'}, {step: 3, title: 'Add data', description: 'Set up databases and authentication through the interface.'}],
    is_published: true, created_at: '2024-11-01', source: 'enriched',
  },
  {
    id: '28', slug: 'windsurf', name: 'Windsurf', tagline: 'AI-native IDE for flow-state development',
    description: 'Codeium\'s AI-native IDE that gives you deep code understanding, agentic AI, and multi-file editing in one seamless experience.',
    long_description: 'Windsurf (by Codeium) is an AI-native IDE that combines deep code understanding with agentic AI capabilities. Features include Cascade for multi-step reasoning, multi-file editing, terminal automation, and a premium free tier. Built for developers who want an integrated AI experience without managing multiple tools. Strong codebase-wide understanding enables context-aware suggestions.',
    website_url: 'https://codeium.com/windsurf', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents', 'Productivity'],
    pricing_tier: 'Free', pricing_min_usd: 0, pricing_max_usd: null,
    use_cases: ['Code Generation', 'Code Review', 'Debugging', 'Refactoring'],
    agent_roles: ['Code Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Desktop (Linux, Mac, Windows)'],
    asia_score: 7, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global', local_pricing_asia: false, best_for_asia_use_case: 'Free AI-powered IDE for Asian developers',
    avg_rating: 4.5, total_ratings: 5600, trending_score: 91, saves_count: 13500,
    how_to_use_guide: 'Install Windsurf as your IDE. Use Cascade for complex multi-step tasks. Cmd+L to chat with AI about your codebase. Free tier includes generous AI usage.',
    playbook_use_cases: ['Full-stack development', 'Code refactoring', 'Code review', 'Bug fixing'],
    playbook_steps: [{title: 'Install Windsurf', description: 'Download the IDE for your platform.'}, {title: 'Open your project', description: 'Windsurf indexes your entire codebase for AI context.'}],
    solopreneur_score: 9, best_for_smallbusiness_use_case: 'Free AI IDE for solopreneur developers', local_language_support: false, supported_languages_detail: 'English interface', ai_ready: true,
    community_rating: 4.5, total_community_reviews: 5600, how_to_use_guide_title: 'Code faster with Windsurf IDE', best_for_pipeline_stage: 'coding',
    quick_start_steps: [{step: 1, title: 'Install Windsurf', description: 'Download and install the free IDE for your platform.'}, {step: 2, title: 'Use Cascade', description: 'Open Cascade for multi-step AI tasks like refactoring or building features.'}, {step: 3, title: 'Chat with codebase', description: 'Use Cmd+L to ask questions about your entire project.'}],
    is_published: true, created_at: '2025-02-01', source: 'enriched',
  },
  {
    id: '29', slug: 'v0', name: 'Vercel v0', tagline: 'AI-powered UI component generation',
    description: 'Generate React components and pages from text prompts using Vercel\'s AI. Built for rapid UI prototyping.',
    long_description: 'Vercel v0 is an AI tool that generates React/Next.js UI components from natural language descriptions. It uses shadcn/ui components by default, generates production-ready TypeScript code, and can create full page layouts. Excellent for rapid UI prototyping. Generated components can be directly used in Next.js projects. Popular among frontend developers and designers.',
    website_url: 'https://v0.dev', logo_url: '',
    category: 'Code & Development', subcategories: ['Design & Creative', 'No-Code & Automation'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: 30,
    use_cases: ['Code Generation', 'UI Design', 'Prototyping'],
    agent_roles: ['Code Assistant', 'Design Assistant'],
    is_agentic: false, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global (US)', local_pricing_asia: true, best_for_asia_use_case: 'Rapid UI component generation for Asian SaaS products',
    avg_rating: 4.6, total_ratings: 7200, trending_score: 93, saves_count: 16200,
    how_to_use_guide: 'Describe the UI you want. v0 generates a React component using shadcn/ui. Copy the code directly into your project or use the CLI.',
    playbook_use_cases: ['UI components', 'Page layouts', 'Form creation', 'Dashboard designs'],
    playbook_steps: [{title: 'Describe your UI', description: 'Tell v0 what component or page you need in detail.'}, {title: 'Copy and use', description: 'Generated code is production-ready. Copy directly into your Next.js project.'}],
    solopreneur_score: 9, best_for_smallbusiness_use_case: 'Rapid UI prototyping for solopreneurs', local_language_support: false, supported_languages_detail: 'English only', ai_ready: true,
    community_rating: 4.6, total_community_reviews: 7200, how_to_use_guide_title: 'Generate React UIs with v0', best_for_pipeline_stage: 'design',
    quick_start_steps: [{step: 1, title: 'Describe your UI', description: 'Type a description like "A pricing table with 3 tiers and a CTA button."'}, {step: 2, title: 'Copy the code', description: 'v0 generates production-ready React/Next.js code.'}, {step: 3, title: 'Integrate into your project', description: 'Copy directly into your codebase. Works with shadcn/ui and Tailwind.'}],
    is_published: true, created_at: '2024-07-01', source: 'enriched',
  },
  {
    id: '30', slug: 'replit-agent', name: 'Replit Agent', tagline: 'Full-stack app development in-browser',
    description: 'Replit\'s AI agent that can build, deploy, and iterate on web applications entirely in your browser.',
    long_description: 'Replit Agent is a complete in-browser development environment with an AI agent that can scaffold, write, run, and deploy web applications. It integrates code editing, runtime, database, and hosting in one platform. Supports Python, Node.js, Go, and many other languages. The AI Agent can autonomously implement features, fix bugs, and deploy. Free tier includes limited agent usage.',
    website_url: 'https://replit.com', logo_url: '',
    category: 'Code & Development', subcategories: ['AI Agents', 'No-Code & Automation'],
    pricing_tier: 'Freemium', pricing_min_usd: 0, pricing_max_usd: 25,
    use_cases: ['Code Generation', 'Full-Stack Apps', 'Deployment', 'Learning'],
    agent_roles: ['Code Assistant', 'Personal Assistant'],
    is_agentic: true, is_multimodal: false, has_api: false, platform: ['Web'],
    asia_score: 6, asia_ready: false, supports_languages: ['English'],
    data_residency: 'Global (US, EU)', local_pricing_asia: true, best_for_asia_use_case: 'In-browser coding without local setup for Asian students and developers',
    avg_rating: 4.1, total_ratings: 11000, trending_score: 78, saves_count: 18900,
    how_to_use_guide: 'Create a Repl. Describe what you want the Agent to build. Review, iterate, and deploy with one click. Free tier includes limited agent cycles per week.',
    playbook_use_cases: ['Web app development', 'Learning', 'API prototyping', 'Data analysis apps'],
    playbook_steps: [{title: 'Create a Repl', description: 'Start a new Repl and choose your tech stack.'}, {title: 'Use Agent', description: 'Describe your app and let the Agent build it.'}],
    solopreneur_score: 7, best_for_smallbusiness_use_case: 'In-browser coding for quick prototyping', local_language_support: false, supported_languages_detail: 'English interface', ai_ready: true,
    community_rating: 4.1, total_community_reviews: 11000, how_to_use_guide_title: 'Build and deploy with Replit Agent', best_for_pipeline_stage: 'coding',
    quick_start_steps: [{step: 1, title: 'Create a Repl', description: 'Pick Python, Node.js, or Go. No local setup needed.'}, {step: 2, title: 'Describe to the Agent', description: 'Tell the Agent what you want to build. It handles implementation.'}, {step: 3, title: 'Deploy', description: 'One-click deploy from the Replit editor.'}],
    is_published: true, created_at: '2024-09-01', source: 'enriched',
  },
];

export default toolsData;
