// Phase 2 enrichment: append fields to each existing tool entry
// Works by finding each tool closing and inserting enrichment before the closing },
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'lib', 'data.ts');
let src = fs.readFileSync(SRC, 'utf-8');

const enrichMap = {
  '1': '  solopreneur_score: 10, best_for_smallbusiness_use_case: "All-round AI assistant for solopreneurs", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Vietnamese, Thai, Indonesian", ai_ready: true, community_rating: 4.7, total_community_reviews: 45200, how_to_use_guide_title: "Master ChatGPT for daily workflows", best_for_pipeline_stage: "all-rounder", quick_start_steps: [{step:1,title:"Start a conversation",description:"Open ChatGPT and type your request naturally."},{step:2,title:"Refine with follow-ups",description:"Ask follow-up questions or request revisions."},{step:3,title:"Custom instructions",description:"Set custom instructions in settings."},{step:4,title:"Explore GPTs",description:"Browse the GPT Store for specialised assistants."},{step:5,title:"Use voice and images",description:"Upload images for analysis or use voice mode."}]',
  '2': '  solopreneur_score: 9, best_for_smallbusiness_use_case: "Deep analysis and document processing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean", ai_ready: true, community_rating: 4.6, total_community_reviews: 32100, how_to_use_guide_title: "Leverage Claude for deep analysis", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Upload documents",description:"Drag and drop PDFs or Word docs."},{step:2,title:"Ask complex questions",description:"Ask Claude to analyse or extract insights."},{step:3,title:"Use projects",description:"Create Projects with custom instructions."},{step:4,title:"Iterate on outputs",description:"Request revisions with specific feedback."},{step:5,title:"Export and share",description:"Copy outputs, share conversation links."}]',
  '3': '  solopreneur_score: 8, best_for_smallbusiness_use_case: "Research and long-form content", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Hindi, Thai, Vietnamese", ai_ready: true, community_rating: 4.3, total_community_reviews: 28100, how_to_use_guide_title: "Get the most from Gemini 2.5", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Open Gemini",description:"Start with a simple question."},{step:2,title:"Use Google ecosystem",description:"Connect to Google Workspace."},{step:3,title:"Leverage long context",description:"Paste entire codebases. 1M+ tokens."},{step:4,title:"Deep research",description:"Multi-source document research."},{step:5,title:"Image and video analysis",description:"Upload for native visual analysis."}]',
  '4': '  solopreneur_score: 8, best_for_smallbusiness_use_case: "Code completion for solo devs", local_language_support: true, supported_languages_detail: "English, Chinese, Japanese", ai_ready: true, community_rating: 4.2, total_community_reviews: 19500, how_to_use_guide_title: "Supercharge your coding with Copilot", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install the extension",description:"Install in VS Code, JetBrains."},{step:2,title:"Start typing",description:"Begin coding. Copilot suggests completions."},{step:3,title:"Write comments",description:"Write a comment describing the code."},{step:4,title:"Use Copilot Chat",description:"Ask about your codebase."},{step:5,title:"Inline fixes",description:"Fix bugs or refactor inline."}]',
  '5': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Product photography and branding visuals", local_language_support: false, supported_languages_detail: "English prompts only", ai_ready: false, community_rating: 4.5, total_community_reviews: 15200, how_to_use_guide_title: "Create stunning visuals with Midjourney", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Join Discord",description:"Midjourney runs on Discord."},{step:2,title:"Write your first prompt",description:"Type /imagine with a description."},{step:3,title:"Upscale and vary",description:"U buttons to upscale, V for variations."},{step:4,title:"Refine with parameters",description:"Use --ar, --s parameters."},{step:5,title:"Use Describe feature",description:"Get prompt ideas from images."}]',
  '6': '  solopreneur_score: 9, best_for_smallbusiness_use_case: "Market research and competitor analysis", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.5, total_community_reviews: 22100, how_to_use_guide_title: "Research like a pro with Perplexity", best_for_pipeline_stage: "research", quick_start_steps: [{step:1,title:"Ask a research question",description:"Type any question with sources."},{step:2,title:"Choose focus mode",description:"Academic, Writing, Math, Social."},{step:3,title:"Explore follow-ups",description:"Auto-suggested deep-dive questions."},{step:4,title:"Create collections",description:"Save queries for ongoing research."},{step:5,title:"Use Pro search",description:"Multi-step reasoning."}]',
  '7': '  solopreneur_score: 10, best_for_smallbusiness_use_case: "Rapid MVP development for solopreneurs", local_language_support: true, supported_languages_detail: "English, Chinese, Japanese", ai_ready: true, community_rating: 4.8, total_community_reviews: 28100, how_to_use_guide_title: "Build apps faster with Cursor AI", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install Cursor",description:"Download Cursor IDE."},{step:2,title:"Use Composer",description:"Cmd+I for multi-file changes."},{step:3,title:"Chat with codebase",description:"Cmd+L to chat about your project."},{step:4,title:"Agent mode",description:"Autonomous coding with Agent."},{step:5,title:"Cursor rules",description:".cursorrules for preferences."}]',
  '8': '  solopreneur_score: 8, best_for_smallbusiness_use_case: "Project management and documentation", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.0, total_community_reviews: 12300, how_to_use_guide_title: "Organise your business with Notion AI", best_for_pipeline_stage: "planning", quick_start_steps: [{step:1,title:"Set up workspace",description:"Create pages for docs and tasks."},{step:2,title:"Use AI features",description:"Cmd+J for Notion AI."},{step:3,title:"Build databases",description:"Task tracking, CRM, calendars."},{step:4,title:"Connect tools",description:"Slack, Drive, Figma integrations."},{step:5,title:"Create templates",description:"Save layouts as templates."}]',
  '9': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Autonomous bug fixing and feature dev", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 3.8, total_community_reviews: 8900, how_to_use_guide_title: "Let Devin handle the coding", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Describe your task",description:"Tell Devin in natural language."},{step:2,title:"Watch it work",description:"Devin uses its own tools."},{step:3,title:"Review changes",description:"Full diff with explanation."},{step:4,title:"Provide feedback",description:"Ask for changes."},{step:5,title:"Deploy",description:"Devin handles deployment."}]',
  '10': '  solopreneur_score: 9, best_for_smallbusiness_use_case: "Social media graphics and presentations", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, Thai, Vietnamese, English", ai_ready: true, community_rating: 4.4, total_community_reviews: 18400, how_to_use_guide_title: "Design everything with Canva AI", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Create a design",description:"Template or Magic Design."},{step:2,title:"Use Magic Studio",description:"Write, Eraser, Animator."},{step:3,title:"Brand kit",description:"Upload logos and colours."},{step:4,title:"Collaborate",description:"Real-time collaboration."},{step:5,title:"Export",description:"Export or schedule social posts."}]',
  '11': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Marketing copy and blog content", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.2, total_community_reviews: 4200, how_to_use_guide_title: "Generate marketing content at scale", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Choose a template",description:"50+ templates."},{step:2,title:"Set brand voice",description:"Define tone and audience."},{step:3,title:"Generate and refine",description:"Multiple versions to choose from."}]',
  '12': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Business writing and email polish", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.3, total_community_reviews: 3800, how_to_use_guide_title: "Write better with Grammarly AI", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Install everywhere",description:"Browser, desktop, mobile."},{step:2,title:"Write confidently",description:"Real-time tone and grammar checks."},{step:3,title:"Set goals",description:"Set tone, audience, formality."}]',
  '13': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Marketing content and copywriting", local_language_support: false, supported_languages_detail: "English only", ai_ready: true, community_rating: 4.2, total_community_reviews: 4200, how_to_use_guide_title: "Generate marketing content at scale", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Start with a workflow",description:"Blog, social, email."},{step:2,title:"Enter details",description:"Topic, keywords, voice."},{step:3,title:"Use Infobase",description:"Brand guidelines for consistency."}]',
  '14': '  solopreneur_score: 6, best_for_smallbusiness_use_case: "AI video content for marketing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English, Spanish", ai_ready: false, community_rating: 4.1, total_community_reviews: 5100, how_to_use_guide_title: "Create AI videos in minutes", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Choose an avatar",description:"160+ avatars."},{step:2,title:"Write your script",description:"Converts to speech."},{step:3,title:"Customise video",description:"Add backgrounds and music."}]',
  '15': '  solopreneur_score: 5, best_for_smallbusiness_use_case: "Custom AI model hosting", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: false, community_rating: 4.6, total_community_reviews: 24100, how_to_use_guide_title: "Explore and deploy open-source AI", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Explore the Hub",description:"500K+ models."},{step:2,title:"Use Spaces",description:"Interactive demos."},{step:3,title:"Deploy with API",description:"Free Inference API."}]',
  '16': '  solopreneur_score: 6, best_for_smallbusiness_use_case: "Building custom AI workflows", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: false, community_rating: 4.3, total_community_reviews: 17200, how_to_use_guide_title: "Build LLM applications", best_for_pipeline_stage: "coding", quick_start_steps: [{step:1,title:"Install LangChain",description:"pip install langchain."},{step:2,title:"Set up LLM",description:"Configure with API key."},{step:3,title:"Build a chain",description:"Prompt + LLM + parser."}]',
  '17': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Voiceovers for content and ads", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.4, total_community_reviews: 9800, how_to_use_guide_title: "Generate professional voiceovers", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Choose a voice",description:"1000+ options."},{step:2,title:"Type or upload",description:"Converts to natural speech."},{step:3,title:"Voice Design",description:"Custom age, gender, accent."}]',
  '18': '  solopreneur_score: 6, best_for_smallbusiness_use_case: "Video editing and generation", local_language_support: false, supported_languages_detail: "English only", ai_ready: false, community_rating: 4.2, total_community_reviews: 7400, how_to_use_guide_title: "Edit video with AI tools", best_for_pipeline_stage: "design", quick_start_steps: [{step:1,title:"Choose a tool",description:"Text-to-Video, Inpainting."},{step:2,title:"Write your prompt",description:"Describe the video."},{step:3,title:"Edit timeline",description:"Transitions and timing."}]',
  '19': '  solopreneur_score: 7, best_for_smallbusiness_use_case: "Podcast and video editing", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.3, total_community_reviews: 6100, how_to_use_guide_title: "Edit audio and video as text", best_for_pipeline_stage: "content", quick_start_steps: [{step:1,title:"Import media",description:"AI transcribes instantly."},{step:2,title:"Edit as text",description:"Delete or rearrange words."},{step:3,title:"Studio Sound",description:"Remove noise, enhance voice."}]',
  '20': '  solopreneur_score: 6, best_for_smallbusiness_use_case: "Customer support automation", local_language_support: true, supported_languages_detail: "Chinese, Japanese, Korean, English", ai_ready: true, community_rating: 4.3, total_community_reviews: 3200, how_to_use_guide_title: "Automate support with Fin", best_for_pipeline_stage: "marketing", quick_start_steps: [{step:1,title:"Connect knowledge base",description:"Fin reads your help articles."},{step:2,title:"Set up Fin",description:"Configure tone and personality."},{step:3,title:"Train with examples",description:"Handle tricky questions."}]',
};

// Process: find each tool block by its id, insert enrichment after last property line
const lines = src.split('\n');
const result = [];
const toolClosings = {}; // toolId -> line numbers to insert after
let prevId = null;

// We need to find the right pattern: each tool entry ends with "  }," on its own line or as last line
// Strategy: for each tool, the enrichment fields go BEFORE the closing "  },"
const insertions = []; // {lineIdx, text}

// Find tool IDs and their closing }, lines
for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  // Look for id pattern
  const idMatch = line.match(/id:\s*'(\d+)'/);
  if (idMatch) prevId = idMatch[1];
  
  // Look for closing }, for the current tool
  if (prevId && enrichMap[prevId]) {
    // This line starts the closing
    if (line.trimStart() === '},' && !line.includes('id:')) {
      // This is the closing line of the current tool
      insertions.push({ lineIdx: i, text: '    ' + enrichMap[prevId] });
      prevId = null;
    }
  }
}

// Insert enrichment in reverse order (to not mess up indices)
insertions.reverse();
for (const ins of insertions) {
  lines.splice(ins.lineIdx, 0, ins.text);
}

fs.writeFileSync(SRC, lines.join('\n'));
console.log(`✅ Enriched ${insertions.length} tools out of expected 20`);

// Verify
const final = fs.readFileSync(SRC, 'utf-8');
const cnt = final.match(/id:\s+'(\d+)'/g);
if (final.includes(',,')) {
  console.error('ERROR: double commas found!');
  process.exit(1);
}
console.log(`Total tools: ${cnt ? cnt.length : 0}`);
