#!/usr/bin/env node
/**
 * Fix Canadian clone content in 21 AI directory geo pages.
 * Uses readFileSync/writeFileSync for direct string replacement.
 *
 * Each country page has Canadian content embedded. This script replaces
 * exact Canadian strings with country-appropriate content.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP = join(__dirname, '..', 'app');

// ─── Country Data ────────────────────────────────────────────────────────────
// Only fields that differ from the Canada template, organized by section.

const FIXES = {};

function addCountry(slug, data) {
  FIXES[slug] = data;
}

// ─── Argentina ────────────────────────────────────────────────────────────────
addCountry('argentina', {
  Q1: "Argentina has a growing AI ecosystem fueled by excellent engineering talent from UBA, UTN, and UNC. The country produces world-class software engineers and is home to Globant, Mercado Libre's AI initiatives, and a thriving fintech/agtech startup scene centered in Buenos Aires, Córdoba, and Rosario.",
  Q2: "Argentina's Personal Data Protection Act (Ley 25.326 / PDPA) imposes strict requirements on how AI tools collect, use, and disclose personal information. The Agencia de Acceso a la Información Pública (AAIP) oversees enforcement. We flag every tool for PDPA compliance, data residency options within Argentina, and alignment with AAIP guidance on AI and automated decision-making.",
  Q3: "Argentina's economy has distinct AI priorities: agtech and precision farming in the Pampas and Rosario, fintech AI in Buenos Aires (payments, lending, wealth management), software development and nearshore services in Córdoba, healthcare AI for Argentina's public health system, natural language tools for Spanish-language requirements across LatAm, and energy AI for Vaca Muerta's oil and gas sector.",
  Q4: "Argentina offers growing AI innovation support. The Ministry of Science and Technology funds research through CONICET and the National Agency for Scientific Research (ANPCyT). The Argentina 4.0 plan supports technology adoption. Tax incentives exist for software and R&D (Ley de Economía del Conocimiento). VC funding is growing through Kaszek Ventures, Monashees, and local government programs supporting tech startups.",
  Q5: "Argentina's AI regulatory framework centers on Ley 25.326 (PDPA) for data protection, enforced by the AAIP. Specific sectors have additional regulations: ANMAT for health AI, BCRA for financial fintech AI, and ENACOM for telecommunications. Argentina follows OECD AI principles and participates in Ibero-American AI ethics discussions.",
  HERO_BADGE: "Argentina-Focused",
  HERO_PITCH: "We rank every tool on PDPA compliance, ARS/USD pricing, Spanish-language support, and Argentine tech ecosystem readiness — so you find tools built for Argentina's unique market.",
  BADGES: 'Spanish / English','ARS/USD Pricing','PDPA Compliant','Dev Talent-Ready',
  WHY_HEADING: "Why Argentina Needs Its Own AI Tool Directory",
  WHY_SUB: "Argentina's AI ecosystem is unique — world-leading software talent meets a distinct regulatory and cultural landscape in LatAm.",
  WHY_T1: "Spanish & English",
  WHY_D1: "Spanish is the official language of Argentina with high English proficiency in tech hubs. We flag every tool for Spanish-language support, Argentina compliance, and LatAm localization — critical for serving markets from Buenos Aires to Mexico City.",
  WHY_T2: "PDPA Compliance",
  WHY_D2: "Argentina's Personal Data Protection Act (PDPA / Ley 25.326), enforced by the AAIP, is one of LatAm's strictest privacy laws. We evaluate tools for Argentine data residency, consent management, and Mercosur cross-border data transfer compliance.",
  WHY_T3: "AgTech & FinTech Hub",
  WHY_D3: "Argentina produces world-class AI talent from UBA, UTN, and Universidad de San Andrés. The startup ecosystem spans fintech (Mercado Pago, Ualá), agtech (Bioceres), and health tech. We prioritize tools that integrate with Argentina's unique commercialization pipeline.",
  CAT_SUB: "Top picks for Argentine teams — rated for PDPA compliance, ARS pricing, and Spanish-language support.",
  ECOSYSTEM_H2: "Argentina's AI Ecosystem Is a LatAm Powerhouse",
  ECOSYSTEM_P: "From Buenos Aires' fintech boom to Córdoba's software clusters, Argentina produces world-class talent across every tech vertical — with a distinct approach to solving emerging-market challenges.",
  CARD1_TITLE: "Buenos Aires — Fintech & Startup Capital 🇦🇷",
  CARD1_DESC: "Buenos Aires is LatAm's leading startup ecosystem outside São Paulo, anchored by the Buenos Aires Tech Hub and top engineering talent from UBA's Exact Sciences School. The ecosystem spans fintech (Mercado Pago, Ualá, Naranja X), e-commerce, and SaaS — driving spinouts that operate across all of LatAm.",
  CARD2_TITLE: "Córdoba — Argentina's Software Valley 🎓",
  CARD2_DESC: "Córdoba has emerged as Argentina's premier software development hub, home to thousands of developers, the Universidad Nacional de Córdoba, and a dense cluster of tech outsourcing and product startups.",
  CARD3_TITLE: "Rosario — AgTech & Biotech Hub 🏢",
  CARD3_DESC: "Rosario, at the heart of Argentina's Pampas agricultural region, has become a hub for agtech and biotech innovation. The city's strong university ecosystem (UNR) feeds into precision farming, crop analytics, and bioinformatics.",
  CARD4_TITLE: "Globally Recognized Software Talent 🔬",
  CARD4_DESC: "Argentina consistently ranks among the world's top countries for software engineering talent. With strong CS programs at UBA, UTN, and UNC, combined with competitive costs and a US-friendly time zone, Argentina offers one of the best nearshore engineering destinations globally.",
  CTA_BADGE: "Built for Argentine Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Argentine Business",
  CTA_P: "No more guessing if a tool complies with PDPA, supports Spanish, or works for Argentine teams. Every tool on Apifeny AI is rated for Argentine data compliance, ARS/USD pricing, and Spanish-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Argentina 2026 · AI tools for Argentine businesses · Argentina AI software · AI writing tools Argentina · AI coding tools Argentina · AI marketing Argentina · Argentina AI directory · AI tools for Argentine startups · enterprise AI tools Argentina · free AI tools Argentina · AI productivity Argentina · Argentine tech stack · AI tools Buenos Aires · AI tools Córdoba · AI tools Rosario",
});

addCountry('austria', {
  Q1: "Austria has a growing AI ecosystem with strong research at TU Wien, JKU Linz (LIT AI Lab), and TU Graz. The startup scene is centered around Vienna's Digital Economy hub, Graz's industrial automation cluster, and Linz's deep learning community — producing AI for manufacturing, healthcare, and fintech.",
  Q2: "Austria's Datenschutzgesetz (DSG) implements EU GDPR with Austrian-specific provisions. The Data Protection Authority (DSB) in Vienna is one of Europe's most active regulators on AI-related privacy matters. We flag every tool for DSG/GDPR compliance, data residency options within Austria/EU, and alignment with the EU AI Act framework.",
  Q3: "Austria's economy has distinct AI priorities: industrial AI and Industry 4.0 for manufacturing (Steyr, Graz, Linz), healthcare AI for Austria's world-class medical system, fintech AI in Vienna (payments, insurtech, regtech), energy AI for renewable grid management and hydropower optimization, and tourism AI for Austria's massive hospitality sector.",
  Q4: "Austria offers extensive AI innovation funding. The FFG (Austrian Research Promotion Agency) provides grants through its Basisprogramm and AI-specific calls. AWS (Austria Wirtschaftsservice) offers innovation vouchers and venture capital co-investments. The Austrian Startup Package provides tax incentives for R&D.",
  Q5: "Austria's AI regulatory framework combines EU GDPR (DSG implementation) with the upcoming EU AI Act. The DSB enforces data protection in AI systems. Sector-specific regulations apply: AGES for health AI, FMA for financial AI. Austria contributes actively to EU AI ethics guidelines.",
  HERO_BADGE: "Austria-Focused",
  HERO_PITCH: "We rank every tool on DSG/GDPR compliance, EUR pricing, German-language support, and Austrian tech ecosystem readiness — so you find tools built for Austria's unique market.",
  BADGES: 'German / English','EUR Pricing','GDPR Compliant','AI Research Hub',
  WHY_HEADING: "Why Austria Needs Its Own AI Tool Directory",
  WHY_SUB: "Austria's AI ecosystem is unique — world-class research is paired with a strong Mittelstand industrial tradition and a central European regulatory landscape.",
  WHY_T1: "German & English",
  WHY_D1: "Austria's official language is German, with strong English proficiency in tech sectors. Vienna is a major EU tech hub. We flag every tool for German-language support, Austrian compliance, and DACH-region localization.",
  WHY_T2: "GDPR & DSG Compliance",
  WHY_D2: "Austria's Datenschutzgesetz (DSG) implements EU GDPR with additional local requirements. The DSB is known for strict enforcement. We evaluate tools for Austrian data residency, consent management, and DSB guidance alignment.",
  WHY_T3: "Vienna AI & Research Hub",
  WHY_D3: "Austria produces top AI research from TU Wien, University of Vienna, and JKU Linz (LIT AI Lab). The Austrian Institute of Technology (AIT) drives applied AI in energy, health, and manufacturing.",
  CAT_SUB: "Top picks for Austrian teams — rated for DSG/GDPR compliance, EUR pricing, and German-language support.",
  ECOSYSTEM_H2: "Austria's AI Ecosystem Is a European Research Powerhouse",
  ECOSYSTEM_P: "From Vienna's world-class research institutes to Graz's industrial automation, Austria combines deep tech heritage with a thriving startup scene — all within the heart of Europe.",
  CARD1_TITLE: "Vienna — Research & Tech Capital 🇦🇹",
  CARD1_DESC: "Vienna consistently ranks among Europe's most livable cities and is Austria's undisputed tech hub. Anchored by TU Wien, the University of Vienna, and the Austrian Institute of Technology (AIT), the city excels in AI for healthcare, manufacturing, and fintech.",
  CARD2_TITLE: "Graz — Industrial AI & Automation 🎓",
  CARD2_DESC: "Graz, home to TU Graz and the Know-Center, is a powerhouse for industrial AI, automation, and cybersecurity. The city's strong ties to automotive and manufacturing make it a hub for Industry 4.0 and smart production.",
  CARD3_TITLE: "Linz — AI & Deep Learning at JKU 🏢",
  CARD3_DESC: "Linz hosts the Johannes Kepler University (JKU) with its renowned LIT AI Lab and Institute for Machine Learning. The city also drives AI in logistics and steel production via voestalpine partnerships.",
  CARD4_TITLE: "EU Research & Innovation Hub 🔬",
  CARD4_DESC: "Austria punches above its weight in EU research funding, consistently ranking among top EU countries for Horizon Europe participation per capita. The FFG, AWS, and Austria's Startup Package offer substantial R&D grants.",
  CTA_BADGE: "Built for Austrian Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Austrian Business",
  CTA_P: "No more guessing if a tool complies with DSG/GDPR, supports German, or works for Austrian teams. Every tool on Apifeny AI is rated for Austrian data compliance, EUR pricing, and German-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Austria 2026 · AI tools for Austrian businesses · Austria AI software · AI writing tools Austria · AI coding tools Austria · AI marketing Austria · Austria AI directory · AI tools Vienna · AI tools Graz · AI tools Linz",
});

addCountry('belgium', {
  Q1: "Belgium has a growing AI ecosystem with world-class research at KU Leuven, Imec, ULB, and UGent. The startup scene is centered around Brussels' EU-tech ecosystem, Leuven's deep tech corridor, and Antwerp's logistics/port automation hub.",
  Q2: "Belgium's privacy framework implements EU GDPR with local additions via the Belgian Data Protection Authority (GBA/APD). We flag every tool for GDPR/Belgian law compliance, data residency options within Belgium/EU, and alignment with GBA guidance on AI and automated decision-making.",
  Q3: "Belgium's economy has distinct AI priorities: port and logistics AI in Antwerp (Europe's second-largest port), pharma and biotech AI for Belgium's world-leading drug industry, fintech and regtech AI in Brussels serving EU financial markets, manufacturing AI for Flanders' industrial corridor, and legal AI for EU regulatory compliance across multiple languages.",
  Q4: "Belgium offers robust AI innovation support. VLAIO (Flanders) and SPW Recherche (Wallonia) provide substantial R&D grants. BELSPO funds AI research programs. Imec's venture arm and KU Leuven R&D support deep tech spinouts.",
  Q5: "Belgium's AI regulatory framework combines EU GDPR with the upcoming EU AI Act. The GBA/APD enforces data protection. Sector-specific regulations apply: FAMHP for health AI, NBB/FSMA for financial AI. Belgium actively participates in EU AI ethics discussions.",
  HERO_BADGE: "Belgium-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, EUR pricing, multilingual (NL/FR/EN) support, and Belgian tech ecosystem readiness — so you find tools built for Belgium's unique market.",
  BADGES: 'Dutch / French / German','EUR Pricing','GDPR Compliant','EU & NATO Hub',
  WHY_HEADING: "Why Belgium Needs Its Own AI Tool Directory",
  WHY_SUB: "Belgium's AI ecosystem is unique — at the crossroads of Europe with trilingual talent, world-class semiconductor AI research, and a strategic position in EU institutions.",
  WHY_T1: "Dutch, French & German",
  WHY_D1: "Belgium is officially trilingual (Dutch, French, German) with strong English proficiency. Brussels hosts the EU and NATO. We flag every tool for multilingual support, Belgian compliance, and Benelux localization.",
  WHY_T2: "GDPR & Belgian Privacy Law",
  WHY_D2: "Belgium's privacy framework implements EU GDPR with local additions via the GBA/APD. We evaluate tools for Belgian data residency, consent management, and EU AI Act alignment.",
  WHY_T3: "Brussels AI Ecosystem",
  WHY_D3: "Belgium produces strong AI research from KU Leuven, ULB, VUB, and UGent. Imec (Leuven) is a world-leading nanoelectronics and AI hardware research center.",
  CAT_SUB: "Top picks for Belgian teams — rated for GDPR compliance, EUR pricing, and multilingual support.",
  ECOSYSTEM_H2: "Belgium's AI Ecosystem Is a European Crossroads",
  ECOSYSTEM_P: "From Brussels' EU connections to Leuven's world-class research, Belgium combines multilingual talent, deep tech heritage, and a strategic position at the heart of Europe.",
  CARD1_TITLE: "Brussels — EU & NATO Capital 🇧🇪",
  CARD1_DESC: "Brussels is the capital of Europe, hosting EU institutions and NATO headquarters. The city's AI scene is driven by ULB and VUB research, a dense network of EU-focused startups, and a booming legal/fintech AI sector.",
  CARD2_TITLE: "Leuven — Imec & Deep Tech 🎓",
  CARD2_DESC: "Leuven is home to KU Leuven and Imec, a world-leading nanoelectronics and AI hardware research center with 5,000+ researchers. The startup ecosystem spans chip design, AI hardware, healthtech, and deep tech.",
  CARD3_TITLE: "Antwerp & Ghent — Port & Pharma AI 🏢",
  CARD3_DESC: "Antwerp, Europe's second-largest port, drives AI in logistics and supply chain. Ghent University and IDLab produce cutting-edge AI in NLP and computer vision, powering biotech drug discovery.",
  CARD4_TITLE: "European Research & Funding Hub 🔬",
  CARD4_DESC: "Belgium's central EU location gives it unmatched access to Horizon Europe and ERC funding. VLAIO, SPW Recherche, and Innoviris provide substantial R&D incentives.",
  CTA_BADGE: "Built for Belgian Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Belgian Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports Dutch/French, or works for Belgian teams. Every tool on Apifeny AI is rated for Belgian data compliance, EUR pricing, and multilingual readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Belgium 2026 · AI tools for Belgian businesses · Belgium AI software · AI writing tools Belgium · AI coding tools Belgium · AI marketing Belgium · Belgium AI directory · AI tools Brussels · AI tools Leuven · AI tools Antwerp",
});

addCountry('chile', {
  Q1: "Chile has a growing AI ecosystem with strong research at UC (PUC) and Universidad de Chile. The startup scene is centered around Santiago's Startup Chile ecosystem, Valparaíso's tech corridor, and Antofagasta's mining tech cluster — producing AI for fintech, mining, and renewable energy.",
  Q2: "Chile's data protection framework is governed by Law No. 19.628 with a new GDPR-aligned bill in progress. The Consejo para la Transparencia (CPLT) oversees data privacy. We flag every tool for Chilean data protection compliance and evolving AI governance frameworks.",
  Q3: "Chile's economy has distinct AI priorities: mining tech and predictive maintenance in Antofagasta and the Atacama region, fintech AI in Santiago (payments, lending, wealth management), renewable energy AI for Chile's massive solar and wind installations, agtech for Chile's fruit and wine export industries, and salmon farming AI for the aquaculture sector.",
  Q4: "Chile offers robust AI innovation support. CORFO provides grants through its InnovaChile programs and Startup Chile accelerators. ANID funds AI research. Tax incentives under the R&D Law benefit tech companies.",
  Q5: "Chile's AI regulatory framework centers on Law 19.628 for data protection. CORFO and the Ministry of Science have published a National AI Policy with ethical guidelines. Sector-specific regulations: CMF for fintech, SERNAGEOMIN for mining AI.",
  HERO_BADGE: "Chile-Focused",
  HERO_PITCH: "We rank every tool on data protection compliance, CLP/USD pricing, Spanish-language support, and Chilean tech ecosystem readiness — so you find tools built for Chile's unique market.",
  BADGES: 'Español & English','CLP/USD Pricing','PDPA Compliant','Startup Chile Hub',
  WHY_HEADING: "Why Chile Needs Its Own AI Tool Directory",
  WHY_SUB: "Chile's AI ecosystem is unique — the most competitive economy in LatAm combined with a world-class Startup Chile accelerator and booming mining/energy AI sector.",
  WHY_T1: "Spanish & English",
  WHY_D1: "Chile has the highest English proficiency in LatAm and is a regional leader in tech innovation. We flag every tool for Spanish-language support, Chilean compliance, and LatAm localization.",
  WHY_T2: "PDPA & Data Protection",
  WHY_D2: "Chile's Law No. 19.628 on Personal Data Protection is being modernized with a new GDPR-aligned bill. The CPLT oversees data privacy.",
  WHY_T3: "Startup Chile & Innovation",
  WHY_D3: "Chile is a LatAm innovation leader, anchored by Startup Chile, strong universities (UC, UChile, USM), and a growing AI ecosystem spanning fintech, mining tech, and renewable energy AI.",
  CAT_SUB: "Top picks for Chilean teams — rated for PDPA compliance, CLP pricing, and Spanish-language support.",
  ECOSYSTEM_H2: "Chile's Tech Ecosystem Is LatAm's Innovation Leader",
  ECOSYSTEM_P: "From Santiago's thriving startup scene to Antofagasta's mining tech revolution, Chile combines political stability, open markets, and a talent pool that punches above its weight.",
  CARD1_TITLE: "Santiago — Startup Capital of LatAm 🇨🇱",
  CARD1_DESC: "Santiago is LatAm's most dynamic startup ecosystem outside Brazil, anchored by Startup Chile, UC's Engineering School, and Universidad de Chile. The city excels in fintech, e-commerce, and SaaS.",
  CARD2_TITLE: "Valparaíso & Viña del Mar — Tech & Creative Hub 🎓",
  CARD2_DESC: "The Valparaíso region is home to the Federico Santa María Technical University (USM) and a growing cluster of tech startups.",
  CARD3_TITLE: "Antofagasta — Mining & Energy Tech 🏢",
  CARD3_DESC: "Antofagasta produces 30% of global copper and is a natural hub for mining tech AI — predictive maintenance, autonomous vehicles, and energy optimization.",
  CARD4_TITLE: "Open Economy & Innovation Gateway 🔬",
  CARD4_DESC: "Chile is LatAm's most competitive economy with strong IP protection, trade agreements covering 65+ markets, and substantial CORFO R&D grants.",
  CTA_BADGE: "Built for Chilean Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Chilean Business",
  CTA_P: "No more guessing if a tool complies with Chilean data protection law, supports Spanish, or works for Chilean teams. Every tool on Apifeny AI is rated for Chile data compliance, CLP/USD pricing, and Spanish-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Chile 2026 · AI tools for Chilean businesses · Chile AI software · AI writing tools Chile · AI coding tools Chile · AI marketing Chile · Chile AI directory · AI tools Santiago · AI tools Valparaíso · AI tools Antofagasta",
});

addCountry('colombia', {
  Q1: "Colombia has a growing AI ecosystem with strong universities (Uniandes, EAFIT, UNAL) and a booming tech scene. The startup ecosystem is centered around Bogotá's fintech hub, Medellín's innovation district (Ruta N), and Cali's emerging tech cluster.",
  Q2: "Colombia's Statutory Law 1581 of 2012 governs personal data protection, enforced by the Superintendencia de Industria y Comercio (SIC). We flag every tool for Law 1581 compliance, data residency options within Colombia, and alignment with SIC guidance.",
  Q3: "Colombia's economy has distinct AI priorities: fintech AI in Bogotá and Medellín (digital payments, lending, insurtech), logistics AI for Colombia's trade corridors, e-commerce AI for the rapidly growing online retail sector, agtech for coffee and flower export industries, and energy AI for Colombia's oil and renewable sectors.",
  Q4: "Colombia offers growing AI innovation support. INNpulsa Colombia provides grants and venture-building programs. Colciencias funds AI research. The Orange Economy law provides tax incentives for creative and tech industries.",
  Q5: "Colombia's AI regulatory framework includes Law 1581 for data protection, with CONPES 3975 (National AI Policy) setting strategic guidelines. Sector-specific regulations: SFC for fintech AI, INVIMA for health AI, MinTIC for digital governance. Colombia participates in OECD AI policy discussions.",
  HERO_BADGE: "Colombia-Focused",
  HERO_PITCH: "We rank every tool on data protection compliance, COP/USD pricing, Spanish-language support, and Colombian tech ecosystem readiness.",
  BADGES: 'Español & English','COP/USD Pricing','PDPA Compliant','Bogotá Tech Hub',
  WHY_HEADING: "Why Colombia Needs Its Own AI Tool Directory",
  WHY_SUB: "Colombia's AI ecosystem is unique — LatAm's third-largest tech talent pool combined with a booming fintech scene in Bogotá and Medellín.",
  WHY_T1: "Spanish & English",
  WHY_D1: "Colombia is LatAm's third-largest tech talent pool with growing English proficiency in tech hubs. We flag every tool for Spanish-language support and Colombian compliance.",
  WHY_T2: "Data Protection Law",
  WHY_D2: "Colombia's Statutory Law 1581 of 2012 governs personal data protection, enforced by the SIC. We evaluate tools for Colombian data residency and SIC guidance.",
  WHY_T3: "Medellín & Bogotá Innovation",
  WHY_D3: "Colombia's tech scene is booming. Medellín won Innovative City of the Year. Universities like Uniandes, EAFIT, and UNAL produce top engineers.",
  CAT_SUB: "Top picks for Colombian teams — rated for data protection compliance, COP pricing, and Spanish-language support.",
  ECOSYSTEM_H2: "Colombia's Tech Ecosystem Is One of LatAm's Fastest Growing",
  ECOSYSTEM_P: "From Bogotá's fintech explosion to Medellín's innovation renaissance, Colombia combines deep tech talent with a rapidly maturing startup ecosystem.",
  CARD1_TITLE: "Bogotá — Fintech & Corporate Hub 🇨🇴",
  CARD1_DESC: "Bogotá is Colombia's largest tech hub with a booming fintech ecosystem (Nequi, Addi, Truora), corporate innovation centers, and top universities (Uniandes, UNAL, Javeriana).",
  CARD2_TITLE: "Medellín — Innovation City 🎓",
  CARD2_DESC: "Medellín transformed from industrial city to global innovation icon, home to EAFIT University, Ruta N innovation district, and thriving fintech, logistics, and creative tech startups.",
  CARD3_TITLE: "Cali — Emerging Tech & Logistics Hub 🏢",
  CARD3_DESC: "Cali is Colombia's third tech pole with a growing software development cluster and Pacific logistics infrastructure. Icesi University and Universidad del Valle produce strong engineering talent.",
  CARD4_TITLE: "Talent Pipeline & Innovation Funding 🔬",
  CARD4_DESC: "Colombia produces 15,000+ engineering graduates annually from Uniandes, EAFIT, UNAL, and Icesi. INNpulsa Colombia and Colciencias provide generous R&D grants.",
  CTA_BADGE: "Built for Colombian Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Colombian Business",
  CTA_P: "No more guessing if a tool complies with Colombian data protection law, supports Spanish, or works for Colombian teams.",
  SEO: "best AI tools in Colombia 2026 · AI tools for Colombian businesses · Colombia AI software · AI writing tools Colombia · AI coding tools Colombia · AI marketing Colombia · Colombia AI directory · AI tools Bogotá · AI tools Medellín · AI tools Cali",
});

addCountry('denmark', {
  Q1: "Denmark has a strong AI ecosystem with world-class research at DTU, University of Copenhagen, and Aarhus University. The startup scene centers on Copenhagen's Pioneer Centre for AI and Aarhus' tech hub — producing AI for healthcare, energy, shipping, and fintech.",
  Q2: "Denmark's Data Protection Act supplements EU GDPR with Danish-specific provisions. Datatilsynet (Danish Data Protection Authority) is highly active on AI guidance. We evaluate tools for Danish data residency, GDPR compliance, and Datatilsynet's AI guidance.",
  Q3: "Denmark's economy has distinct AI priorities: healthcare AI leveraging Denmark's digitized health records, shipping and logistics AI (Maersk, DFDS), green energy AI for wind and district heating, fintech AI in Copenhagen, and agtech AI for Denmark's world-leading agriculture sector.",
  Q4: "Denmark offers extensive AI innovation funding. Innovation Fund Denmark invests in AI research and commercialization. The Danish Growth Fund provides venture capital. EU Horizon Europe and EIC grants are accessible through Denmark's strong EU network.",
  Q5: "Denmark's AI regulatory framework combines EU GDPR with the Danish Data Protection Act. Datatilsynet enforces AI-related privacy. Sector regulations: Lægemiddelstyrelsen for health AI, Finanstilsynet for financial AI. Denmark's Data Ethics Seal is a pioneering framework.",
  HERO_BADGE: "Denmark-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, DKK/EUR pricing, Danish-language support, and Danish tech ecosystem readiness — so you find tools built for Denmark's unique market.",
  BADGES: 'Danish & English','DKK/EUR Pricing','GDPR Compliant','Nordic Innovation Hub',
  WHY_HEADING: "Why Denmark Needs Its Own AI Tool Directory",
  WHY_SUB: "Denmark's AI ecosystem is unique — a highly digitized society with world-leading healthcare data, green energy innovation, and a strong tradition of responsible AI.",
  WHY_T1: "Danish & English",
  WHY_D1: "Denmark has near-universal English proficiency alongside Danish as the official language. Copenhagen is a major Nordic tech hub. We flag every tool for Danish language support and Nordic localization.",
  WHY_T2: "GDPR & Danish Data Law",
  WHY_D2: "Denmark's Data Protection Act supplements EU GDPR with Danish-specific provisions. Datatilsynet is highly active on AI guidance. We evaluate tools for Danish data residency.",
  WHY_T3: "Copenhagen AI Ecosystem",
  WHY_D3: "Denmark produces world-class AI research from DTU, University of Copenhagen, and Aarhus University. Innovation Fund Denmark invests heavily in AI research and commercialization.",
  CAT_SUB: "Top picks for Danish teams — rated for GDPR compliance, DKK pricing, and Danish-language support.",
  ECOSYSTEM_H2: "Denmark's AI Ecosystem Is a Nordic Innovation Leader",
  ECOSYSTEM_P: "From Copenhagen's world-class research to Aarhus' AI startups, Denmark combines a digitized society, green energy leadership, and a strong tradition of responsible AI.",
  CARD1_TITLE: "Copenhagen — Nordic AI Hub 🇩🇰",
  CARD1_DESC: "Copenhagen is Scandinavia's leading tech hub, anchored by DTU and University of Copenhagen. The city drives AI in healthcare, shipping (Maersk), and clean energy. The Pioneer Centre for AI coordinates Denmark's national AI research.",
  CARD2_TITLE: "Aarhus — Research & Innovation Hub 🎓",
  CARD2_DESC: "Aarhus University is a powerhouse for AI research in NLP, robotics, and computational social science. The innovation district hosts a growing cluster of AI startups in health tech and agtech.",
  CARD3_TITLE: "Aalborg — Industrial AI & Smart Systems 🏢",
  CARD3_DESC: "Aalborg University (AAU) is renowned for industrial AI in smart manufacturing, energy systems, and the built environment with strong Danish manufacturing partnerships.",
  CARD4_TITLE: "Nordic Innovation & Green AI Hub 🔬",
  CARD4_DESC: "Innovation Fund Denmark invests heavily in AI. The Danish Data Ethics Seal creates a unique environment for responsible AI. Combined with world-class healthcare data and energy infrastructure, Denmark is ideal for AI with societal impact.",
  CTA_BADGE: "Built for Danish Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Danish Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports Danish, or works for Danish teams. Every tool on Apifeny AI is rated for Danish data compliance, DKK pricing, and Danish-language readiness.",
  SEO: "best AI tools in Denmark 2026 · AI tools for Danish businesses · Denmark AI software · AI writing tools Denmark · AI coding tools Denmark · AI marketing Denmark · Denmark AI directory · AI tools Copenhagen · AI tools Aarhus · AI tools Aalborg",
});

console.log(`\nScript generated successfully with ${Object.keys(FIXES).length} countries defined.`);
console.log('To use: node scripts/fix-geo.mjs');
console.log('Note: Country data loaded into FIXES object.');
console.log('The main processing loop goes below this data declaration.');

addCountry('finland', {
  Q1: "Finland has a strong AI ecosystem with world-class research at Aalto University, University of Helsinki (Finnish Center for AI / FCAI), and Tampere University. The startup scene centers on Helsinki's gaming/healthtech hub, Espoo's deep tech corridor, and Tampere's industrial AI cluster.",
  Q2: "Finland's Data Protection Act implements EU GDPR, enforced by the Office of the Data Protection Ombudsman. We flag every tool for GDPR compliance, Finnish data residency, and alignment with the national AI ethics guidelines.",
  Q3: "Finland's economy has distinct AI priorities: gaming AI for the world-leading game industry (Rovio, Supercell), healthtech and biotech AI leveraging Finland's biobanks, clean tech and energy AI for renewable and circular economy, industrial AI for smart manufacturing, and telecom AI for 5G/6G networks.",
  Q4: "Finland offers extensive AI innovation funding. Business Finland provides substantial R&D grants and innovation funding. VTT Technical Research Centre supports deep tech commercialization. The Finnish AI Accelerator (FAIA) supports AI startups.",
  Q5: "Finland's AI regulatory framework combines EU GDPR with the Finnish Data Protection Act. Sector-specific regulations: Fimea for health AI, FIN-FSA for financial AI. Finland's national AI strategy (Alandri's AI) sets ethical guidelines for responsible AI development.",
  HERO_BADGE: "Finland-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, EUR pricing, Finnish-language support, and Finnish tech ecosystem readiness — so you find tools built for Finland's unique market.",
  BADGES: 'Finnish & English','EUR Pricing','GDPR Compliant','Gaming & Health AI',
  WHY_HEADING: "Why Finland Needs Its Own AI Tool Directory",
  WHY_SUB: "Finland's AI ecosystem is unique — world-leading education, gaming industry, and healthtech innovation combined with the world-renowned Finnish Center for AI.",
  WHY_T1: "Finnish & English",
  WHY_D1: "Finland has excellent English proficiency alongside Finnish and Swedish as official languages. We flag every tool for Finnish language support and Nordic localization.",
  WHY_T2: "GDPR & Finnish Data Law",
  WHY_D2: "Finland's Data Protection Act implements EU GDPR, enforced by the Office of the Data Protection Ombudsman. We evaluate tools for Finnish data residency.",
  WHY_T3: "Helsinki AI & FCAI Hub",
  WHY_D3: "Finland produces world-class AI research from Aalto University, University of Helsinki (FCAI), and Tampere University. Business Finland and VTT accelerate AI commercialization.",
  CAT_SUB: "Top picks for Finnish teams — rated for GDPR compliance, EUR pricing, and Finnish-language support.",
  ECOSYSTEM_H2: "Finland's AI Ecosystem Is a Nordic Powerhouse",
  ECOSYSTEM_P: "From Helsinki's gaming/healthtech hub to Tampere's industrial AI, Finland combines world-class education with deep tech innovation and a thriving startup ecosystem.",
  CARD1_TITLE: "Helsinki — Nordic AI Powerhouse 🇫🇮",
  CARD1_DESC: "Helsinki is a global hub for AI and gaming, anchored by Aalto University and the University of Helsinki (home to the Finnish Center for AI / FCAI).",
  CARD2_TITLE: "Espoo — Deep Tech & Research Corridor 🎓",
  CARD2_DESC: "Espoo hosts Aalto University, VTT, and Nokia's R&D campus. The Otaniemi innovation district is Northern Europe's largest concentration of deep tech.",
  CARD3_TITLE: "Tampere — Industrial AI & Smart Systems 🏢",
  CARD3_DESC: "Tampere University drives AI in industrial automation, machine vision, and smart systems. The city's strong manufacturing heritage combines with cutting-edge AI for smart factories.",
  CARD4_TITLE: "World-Class Education & Innovation Ecosystem 🔬",
  CARD4_DESC: "Finland consistently ranks among the world's most innovative countries. Business Finland offers generous R&D grants and innovation support programs.",
  CTA_BADGE: "Built for Finnish Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Finnish Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports Finnish, or works for Finnish teams. Every tool on Apifeny AI is rated for Finnish data compliance, EUR pricing, and Finnish-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Finland 2026 · AI tools for Finnish businesses · Finland AI software · AI writing tools Finland · AI coding tools Finland · AI marketing Finland · Finland AI directory · AI tools Helsinki · AI tools Espoo · AI tools Tampere",
});

addCountry('ireland', {
  Q1: "Ireland has a thriving AI ecosystem with strong research at Trinity College Dublin, UCD, and the Insight Centre for Data Analytics. The startup scene centers on Dublin's Silicon Docks ecosystem, Cork's pharma-tech hub, and Galway's medtech cluster — producing AI for enterprise SaaS, fintech, and health tech.",
  Q2: "Ireland's Data Protection Act implements EU GDPR. The Irish Data Protection Commission (DPC) is Europe's most influential data regulator for global tech — it's the lead authority for Meta, Google, Apple, TikTok and others. We flag every tool for GDPR compliance, Irish data residency, and DPC guidance.",
  Q3: "Ireland's economy has distinct AI priorities: enterprise SaaS and cloud AI for the multinational tech sector (Google, Meta, Apple, Microsoft), pharma and biotech AI in Cork and the west, fintech AI in Dublin's IFSC, medtech AI in Galway, and agrifood AI for Ireland's massive agriculture and food export industry.",
  Q4: "Ireland offers generous AI innovation support. Enterprise Ireland provides R&D grants and commercialization support. IDA Ireland supports AI FDI. Science Foundation Ireland (SFI) funds AI research through Insight and ADAPT centres. R&D tax credits of 25% benefit tech companies.",
  Q5: "Ireland's AI regulatory framework combines EU GDPR with the Irish Data Protection Act. The DPC is Europe's most active AI-related privacy regulator. Sector regulations: HPRA for health AI, Central Bank of Ireland for financial AI. Ireland's national AI strategy (AI - Here for Good) sets ethical guidelines.",
  HERO_BADGE: "Ireland-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, EUR pricing, English-language support, and Irish tech ecosystem readiness — so you find tools built for Ireland's unique market.",
  BADGES: 'English & Irish','EUR Pricing','GDPR Compliant','EU Tech Gateway',
  WHY_HEADING: "Why Ireland Needs Its Own AI Tool Directory",
  WHY_SUB: "Ireland's AI ecosystem is unique — home to the EU headquarters of the world's largest tech companies, a thriving indigenous startup scene, and Europe's leading data protection regulator.",
  WHY_T1: "English & Irish",
  WHY_D1: "Ireland is predominantly English-speaking with Irish (Gaeilge) as the first official language. Dublin's Silicon Docks hosts the EMEA HQ of 10+ global tech giants. We flag every tool for Irish localization.",
  WHY_T2: "GDPR & Irish Data Law",
  WHY_D2: "Ireland's Data Protection Act implements EU GDPR. The DPC is Europe's most influential data regulator, serving as lead authority for Meta, Google, Apple, and TikTok.",
  WHY_T3: "Dublin Tech & FDI Hub",
  WHY_D3: "Ireland offers a 12.5% corporate tax rate, strong R&D tax credits, and access to EU talent. Enterprise Ireland and IDA Ireland actively support AI startups and FDI.",
  CAT_SUB: "Top picks for Irish teams — rated for GDPR compliance, EUR pricing, and English-language support.",
  ECOSYSTEM_H2: "Ireland's AI Ecosystem Is a European Tech Powerhouse",
  ECOSYSTEM_P: "From Dublin's Silicon Docks to Galway's medtech corridor, Ireland combines multinational tech scale with a thriving indigenous startup ecosystem.",
  CARD1_TITLE: "Dublin — European Tech Capital 🇮🇪",
  CARD1_DESC: "Dublin is home to the European headquarters of Google, Meta, Apple, Microsoft, and LinkedIn. Trinity College Dublin and UCD produce world-class CS talent.",
  CARD2_TITLE: "Cork — Pharma & Manufacturing AI 🎓",
  CARD2_DESC: "Cork hosts UCC and a massive pharmaceutical cluster. The city drives AI in drug discovery, clinical trials, and smart manufacturing. Tyndall National Institute leads in AI hardware.",
  CARD3_TITLE: "Galway — MedTech & Creative AI 🏢",
  CARD3_DESC: "Galway is a global medtech hub (Boston Scientific, Medtronic), anchored by NUI Galway and CÚRAM. The city's creative AI scene spans animation, VR, and digital media.",
  CARD4_TITLE: "EU Gateway & Talent Magnet 🔬",
  CARD4_DESC: "Ireland offers one of the world's most attractive tech tax regimes (12.5% corporate tax), strong R&D tax credits, and a deep multilingual talent pool making it a magnet for AI companies targeting the European market.",
  CTA_BADGE: "Built for Irish Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Irish Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports English, or works for Irish teams. Every tool on Apifeny AI is rated for Irish data compliance, EUR pricing, and English-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Ireland 2026 · AI tools for Irish businesses · Ireland AI software · AI writing tools Ireland · AI coding tools Ireland · AI marketing Ireland · Ireland AI directory · AI tools Dublin · AI tools Cork · AI tools Galway",
});

addCountry('israel', {
  Q1: "Israel has a world-class AI ecosystem with research at Weizmann Institute, Technion, and Hebrew University. The startup scene centers on Tel Aviv's Silicon Wadi, Haifa's deep tech corridor, and Jerusalem's biotech cluster — producing AI for cybersecurity, fintech, and health tech.",
  Q2: "Israel's Privacy Protection Act (1981) governs data protection, enforced by the Privacy Protection Authority. A GDPR-aligned update is in progress. We flag every tool for Israeli data protection compliance and evolving AI governance frameworks.",
  Q3: "Israel's economy has distinct AI priorities: cybersecurity AI in Tel Aviv and Be'er Sheva, fintech AI for the startup ecosystem, health AI leveraging Israel's digitized healthcare system, agtech AI for precision agriculture, and autonomous systems and defense AI.",
  Q4: "Israel offers extensive AI innovation support. The Israel Innovation Authority provides R&D grants through multiple tracks. OurCrowd and other VC platforms connect AI startups to global capital. TASE has specific tech listing paths.",
  Q5: "Israel's AI regulatory framework centers on the Privacy Protection Act with the AI Regulation Bill in progress. Sector regulations: Ministry of Health for medical AI, Bank of Israel for financial AI. Israel National Digital Agency published AI ethics guidelines.",
  HERO_BADGE: "Israel-Focused",
  HERO_PITCH: "We rank every tool on privacy compliance, ILS/USD pricing, Hebrew/English support, and Israeli tech ecosystem readiness — so you find tools built for Israel's unique market.",
  BADGES: 'Hebrew & English','ILS/USD Pricing','Privacy Compliant','Startup Nation',
  WHY_HEADING: "Why Israel Needs Its Own AI Tool Directory",
  WHY_SUB: "Israel's AI ecosystem is unique — the Startup Nation with the highest density of startups per capita, world-class cybersecurity and deep tech research.",
  WHY_T1: "Hebrew & English",
  WHY_D1: "Hebrew is the official language with near-universal English proficiency in tech. Israel's Startup Nation culture is English-friendly. We flag every tool for Hebrew support and Israeli localization.",
  WHY_T2: "Privacy Protection Act",
  WHY_D2: "Israel's Privacy Protection Act (1981) governs data protection, enforced by the Privacy Protection Authority. A GDPR-aligned update is in progress.",
  WHY_T3: "Startup Nation Innovation",
  WHY_D3: "Israel has the highest density of startups per capita globally. The Innovation Authority offers substantial R&D grants. Military technology units (Unit 8200, Talpiot) produce top AI talent.",
  CAT_SUB: "Top picks for Israeli teams — rated for privacy compliance, ILS pricing, and Hebrew/English support.",
  ECOSYSTEM_H2: "Israel's AI Ecosystem Is a Global Startup Powerhouse",
  ECOSYSTEM_P: "From Tel Aviv's Silicon Wadi to Haifa's deep tech corridor, Israel produces more startups per capita than any other country — driven by world-class research and entrepreneurial culture.",
  CARD1_TITLE: "Tel Aviv — Startup Nation Capital 🇮🇱",
  CARD1_DESC: "Tel Aviv is one of the world's top startup ecosystems per capita, anchored by Weizmann Institute, Tel Aviv University, and the thriving Silicon Wadi ecosystem.",
  CARD2_TITLE: "Haifa — Deep Tech & Research Hub 🎓",
  CARD2_DESC: "Haifa is home to the Technion (the 'MIT of Israel'), with major R&D labs from IBM, Intel, and Apple. The city excels in computer vision, NLP, and AI hardware.",
  CARD3_TITLE: "Jerusalem — BioTech & Academic AI 🏢",
  CARD3_DESC: "Jerusalem hosts Hebrew University and the Safra Center for AI. The city's biotech AI ecosystem spans life sciences and the unique blend of academic excellence and startup energy.",
  CARD4_TITLE: "Startup Nation — Global AI Innovation 🔬",
  CARD4_DESC: "Israel has the highest density of startups per capita globally. The Innovation Authority offers substantial R&D grants. Military technology units produce top AI talent.",
  CTA_BADGE: "Built for Israeli Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Israeli Business",
  CTA_P: "No more guessing if a tool complies with Israel's privacy laws, supports Hebrew, or works for Israeli teams. Every tool on Apifeny AI is rated for Israeli data compliance, ILS pricing, and Hebrew-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Israel 2026 · AI tools for Israeli businesses · Israel AI software · AI writing tools Israel · AI coding tools Israel · AI marketing Israel · Israel AI directory · AI tools Tel Aviv · AI tools Haifa · AI tools Jerusalem",
});

addCountry('italy', {
  Q1: "Italy has a growing AI ecosystem with strong research at Politecnico di Milano, Sapienza Rome, and Politecnico di Torino. The startup scene centers on Milan's fintech/fashion hub, Turin's automotive AI cluster, and Rome's public sector AI ecosystem.",
  Q2: "Italy's Data Protection Code (Codice in materia di protezione dei dati personali) implements EU GDPR, enforced by the Garante — one of Europe's most active DPAs. We flag every tool for GDPR compliance, Italian data residency, and Garante guidance.",
  Q3: "Italy's economy has distinct AI priorities: manufacturing AI for Industry 4.0 (automotive, machinery, robotics), fashion and design AI for the Made in Italy brand, fintech AI in Milan, tourism AI for Italy's massive hospitality sector, and agrifood AI for world-leading food production.",
  Q4: "Italy offers growing AI innovation support through the Ministry of Enterprises and Made in Italy (MIMIT). The National AI Strategy funds research. CDP Venture Capital invests in AI startups. Tax incentives for R&D include Credito d'Imposta Ricerca & Sviluppo.",
  Q5: "Italy's AI regulatory framework combines EU GDPR with the Italian Data Protection Code. The Garante enforces AI-related privacy. Sector regulations: AIFA for health AI, CONSOB for financial AI. Italy's National AI Strategy sets ethical guidelines. Italy is an active EU AI Act participant.",
  HERO_BADGE: "Italy-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, EUR pricing, Italian-language support, and Italian tech ecosystem readiness — so you find tools built for Italy's unique market.",
  BADGES: 'Italian & English','EUR Pricing','GDPR Compliant','Fashion & Manufacturing AI',
  WHY_HEADING: "Why Italy Needs Its Own AI Tool Directory",
  WHY_SUB: "Italy's AI ecosystem is unique — the EU's second-largest manufacturing economy combined with world-leading fashion, automotive, and food industries.",
  WHY_T1: "Italian & English",
  WHY_D1: "Italian is the official language with growing English proficiency in tech hubs like Milan and Turin. We flag every tool for Italian-language support and Italian localization.",
  WHY_T2: "GDPR & Italian Data Law",
  WHY_D2: "Italy's Data Protection Code implements EU GDPR. The Garante is one of Europe's most active DPAs. We evaluate tools for Italian data residency.",
  WHY_T3: "Milan AI & Innovation Hub",
  WHY_D3: "Italy produces strong AI research from Politecnico di Milano, Sapienza Rome, and Politecnico di Torino. The Italian Institute of Technology (IIT) drives cutting-edge robotics and AI research.",
  CAT_SUB: "Top picks for Italian teams — rated for GDPR compliance, EUR pricing, and Italian-language support.",
  ECOSYSTEM_H2: "Italy's AI Ecosystem Is a European Innovation Engine",
  ECOSYSTEM_P: "From Milan's fintech and fashion AI to Turin's automotive innovation, Italy combines industrial heritage with cutting-edge AI across manufacturing, design, and food.",
  CARD1_TITLE: "Milan — Economic & Fintech Hub 🇮🇹",
  CARD1_DESC: "Milan is Italy's economic and financial capital, driving AI in fintech, fashion tech, and enterprise SaaS. Home to Politecnico di Milano (top engineering school) and Bocconi University.",
  CARD2_TITLE: "Turin — Automotive & Aerospace AI 🎓",
  CARD2_DESC: "Turin, home to Politecnico di Torino and the Italian Institute of Technology (IIT), is a hub for AI in automotive (Fiat/Stellantis), aerospace, and advanced manufacturing.",
  CARD3_TITLE: "Rome — Research & Public Sector AI 🏢",
  CARD3_DESC: "Rome hosts Sapienza University (Europe's largest by enrollment), the CNR (National Research Council), and a growing AI ecosystem serving Italy's public administration, healthcare, and defense sectors.",
  CARD4_TITLE: "Made in Italy — AI for Manufacturing & Design 🔬",
  CARD4_DESC: "Italy is the EU's second-largest manufacturing economy. The National Research Plan funds AI research through the National AI Strategy. Combined with world-leading industrial design, fashion, and automotive sectors.",
  CTA_BADGE: "Built for Italian Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Italian Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports Italian, or works for Italian teams. Every tool on Apifeny AI is rated for Italian data compliance, EUR pricing, and Italian-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Italy 2026 · AI tools for Italian businesses · Italy AI software · AI writing tools Italy · AI coding tools Italy · AI marketing Italy · Italy AI directory · AI tools Milan · AI tools Turin · AI tools Rome",
});

addCountry('mexico', {
  Q1: "Mexico has a growing AI ecosystem with strong research at UNAM, ITESM (Tec de Monterrey), and IPN. The startup scene centers on Mexico City's fintech hub, Guadalajara's innovation district, and Monterrey's industrial tech cluster — producing AI for fintech, manufacturing, and nearshore services.",
  Q2: "Mexico's Federal Law on Protection of Personal Data Held by Private Parties (LFPDPPP) governs data protection, enforced by the INAI. We flag every tool for LFPDPPP compliance, data residency options within Mexico, and INAI AI guidance.",
  Q3: "Mexico's economy has distinct AI priorities: fintech AI in Mexico City (the largest fintech market in LatAm), nearshore and manufacturing AI across the industrial corridor, automotive AI for Mexico's massive auto manufacturing sector, energy AI for PEMEX and renewables, and telecommunications AI for America Movil.",
  Q4: "Mexico offers growing AI innovation support through CONAHCYT (National Council for Science and Technology). ProMexico (under SE) supports tech exports. The fintech law (Ley Fintech) provides regulatory clarity. VC is growing through funds like Variv Capital, ALLVP, and DILA Capital.",
  Q5: "Mexico's AI regulatory framework includes the LFPDPPP for data protection. Sector-specific regulations: CONDUSEF for fintech AI, COFEPRIS for health AI. Mexico's National AI Strategy (Inteligencia Artificial para el Desarrollo Sostenible) sets ethical guidelines.",
  HERO_BADGE: "Mexico-Focused",
  HERO_PITCH: "We rank every tool on LFPDPPP compliance, MXN/USD pricing, Spanish-language support, and Mexican tech ecosystem readiness — so you find tools built for Mexico's unique market.",
  BADGES: 'Español & English','MXN/USD Pricing','LFPDPPP Compliance','Fintech Hub MEX',
  WHY_HEADING: "Why Mexico Needs Its Own AI Tool Directory",
  WHY_SUB: "Mexico's AI ecosystem is unique — LatAm's second-largest economy with a booming fintech sector, world-class nearshore talent, and strong ties to the US market.",
  WHY_T1: "Spanish & English",
  WHY_D1: "Spanish is the official language with strong English proficiency in tech hubs like Mexico City and Guadalajara. We flag every tool for Mexican Spanish support and LatAm localization.",
  WHY_T2: "LFPDPPP Compliance",
  WHY_D2: "Mexico's Federal Law on Protection of Personal Data (LFPDPPP), enforced by INAI, is one of LatAm's most comprehensive privacy laws. We evaluate tools for Mexican data residency.",
  WHY_T3: "Mexico City Innovation Hub",
  WHY_D3: "Mexico produces strong tech talent from UNAM, Tec de Monterrey, and IPN. The fintech ecosystem (Mercado Pago, Konfio, Clip) is the largest in LatAm outside Brazil.",
  CAT_SUB: "Top picks for Mexican teams — rated for LFPDPPP compliance, MXN pricing, and Spanish-language support.",
  ECOSYSTEM_H2: "Mexico's Tech Ecosystem Is LatAm's Nearshore Powerhouse",
  ECOSYSTEM_P: "From Mexico City's fintech revolution to Guadalajara's innovation district, Mexico combines a massive domestic market with world-class nearshore tech talent.",
  CARD1_TITLE: "Mexico City — Fintech & Corporate Hub 🇲🇽",
  CARD1_DESC: "Mexico City is LatAm's largest fintech market and home to the highest concentration of startups in the region. Anchored by UNAM and ITAM, the ecosystem spans fintech, e-commerce, and SaaS.",
  CARD2_TITLE: "Guadalajara — Mexico's Innovation District 🎓",
  CARD2_DESC: "Guadalajara is known as Mexico's 'Silicon Valley', home to a massive tech cluster including Oracle, Intel, HP, and over 1,000 tech companies. Tec de Monterrey's Guadalajara campus produces top engineering talent.",
  CARD3_TITLE: "Monterrey — Industrial & Manufacturing AI 🏢",
  CARD3_DESC: "Monterrey, Mexico's industrial capital, drives AI in advanced manufacturing, automotive, and steel production. ITESM (Tec de Monterrey) is one of LatAm's top private universities.",
  CARD4_TITLE: "Nearshore & US Market Gateway 🔬",
  CARD4_DESC: "Mexico is the world's #1 nearshore destination for US tech companies. With shared time zones, deep talent pools, and competitive costs, Mexico offers unmatched proximity to the $30T US market.",
  CTA_BADGE: "Built for Mexican Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Mexican Business",
  CTA_P: "No more guessing if a tool complies with LFPDPPP, supports Spanish, or works for Mexican teams. Every tool on Apifeny AI is rated for Mexican data compliance, MXN pricing, and Spanish-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Mexico 2026 · AI tools for Mexican businesses · Mexico AI software · AI writing tools Mexico · AI coding tools Mexico · AI marketing Mexico · Mexico AI directory · AI tools Mexico City · AI tools Guadalajara · AI tools Monterrey",
});

addCountry('netherlands', {
  Q1: "The Netherlands has a thriving AI ecosystem with world-class research at TU Delft, University of Amsterdam (Amsterdam Machine Learning Lab), and TU Eindhoven. The startup scene centers on Amsterdam's Data Science ecosystem, Eindhoven's High Tech Campus, and Utrecht's research corridor.",
  Q2: "The Netherlands' privacy framework implements EU GDPR with local additions via the Dutch Data Protection Authority (Autoriteit Persoonsgegevens / AP). We flag every tool for GDPR compliance, Dutch data residency, and AP guidance on AI and automated decision-making.",
  Q3: "The Netherlands' economy has distinct AI priorities: logistics and supply chain AI at Rotterdam (Europe's largest port), agtech and food AI for the world's second-largest agricultural exporter, fintech AI in Amsterdam, health AI leveraging world-class medical research, and water management and climate AI.",
  Q4: "The Netherlands offers extensive AI innovation support. The Dutch Research Council (NWO) funds AI research through the National AI Coalition (NL AIC). Innovation credits (WBSO) provide tax incentives for R&D. Invest-NL and regional funds support AI startups.",
  Q5: "The Netherlands' AI regulatory framework combines EU GDPR with the Dutch GDPR Implementation Act. The AP enforces AI-related privacy. Sector regulations: IGJ for health AI, AFM for financial AI. The Netherlands' National AI Strategy and NL AIC set ethical guidelines.",
  HERO_BADGE: "Netherlands-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, EUR pricing, Dutch-language support, and Dutch tech ecosystem readiness — so you find tools built for the Netherlands' unique market.",
  BADGES: 'Dutch & English','EUR Pricing','GDPR Compliant','AI & Logistics Hub',
  WHY_HEADING: "Why the Netherlands Needs Its Own AI Tool Directory",
  WHY_SUB: "The Netherlands' AI ecosystem is unique — a highly digitized, English-proficient nation with world-leading logistics, agtech, and water management sectors.",
  WHY_T1: "Dutch & English",
  WHY_D1: "The Netherlands has the highest English proficiency in continental Europe. We flag every tool for Dutch-language support and Benelux localization.",
  WHY_T2: "GDPR & Dutch Privacy Law",
  WHY_D2: "The Dutch Data Protection Authority (AP) is one of Europe's most active regulators. We evaluate tools for Dutch data residency and AP guidance on AI.",
  WHY_T3: "Amsterdam AI & Innovation Hub",
  WHY_D3: "The Netherlands produces world-class AI research from TU Delft, UvA, and TU Eindhoven. The AMLab and NL AIC coordinate national AI efforts.",
  CAT_SUB: "Top picks for Dutch teams — rated for GDPR compliance, EUR pricing, and Dutch-language support.",
  ECOSYSTEM_H2: "The Netherlands' AI Ecosystem Is a European Digital Leader",
  ECOSYSTEM_P: "From Amsterdam's data science community to Eindhoven's High Tech Campus, the Netherlands combines world-class digital infrastructure with a globally connected economy.",
  CARD1_TITLE: "Amsterdam — Data Science & Fintech Hub 🇳🇱",
  CARD1_DESC: "Amsterdam is a top European tech hub, anchored by the University of Amsterdam (AMLab), VU Amsterdam, and a thriving fintech/blockchain/scaling startup ecosystem. The city ranks among Europe's top 3 startup ecosystems.",
  CARD2_TITLE: "Eindhoven — High Tech & Manufacturing AI 🎓",
  CARD2_DESC: "Eindhoven's High Tech Campus is one of Europe's most concentrated tech ecosystems, home to ASML, Philips, and TU Eindhoven. The city drives AI in semiconductors, medical devices, and smart manufacturing.",
  CARD3_TITLE: "Rotterdam — Port & Logistics AI 🏢",
  CARD3_DESC: "Rotterdam, Europe's largest port, is a natural hub for AI in logistics, supply chain, and maritime technology. Erasmus University Rotterdam drives research in AI for business and economics.",
  CARD4_TITLE: "National AI Coalition & Ecosystem 🔬",
  CARD4_DESC: "The NL AIC coordinates national AI research and innovation. WBSO R&D tax credits (up to 32% of R&D wage costs) and Invest-NL provide substantial support for AI startups.",
  CTA_BADGE: "Built for Dutch Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your Dutch Business",
  CTA_P: "No more guessing if a tool complies with GDPR, supports Dutch, or works for Dutch teams. Every tool on Apifeny AI is rated for Dutch data compliance, EUR pricing, and Dutch-language readiness. Start exploring — no account needed.",
  SEO: "best AI tools in Netherlands 2026 · AI tools for Dutch businesses · Netherlands AI software · AI writing tools Netherlands · AI coding tools Netherlands · AI marketing Netherlands · Netherlands AI directory · AI tools Amsterdam · AI tools Rotterdam · AI tools Eindhoven",
});

addCountry('new-zealand', {
  Q1: "New Zealand has a growing AI ecosystem with strong research at the University of Auckland, University of Waikato, and Victoria University of Wellington. The startup scene centers on Auckland's growing tech hub, Wellington's creative tech cluster, and Christchurch's emerging innovation ecosystem.",
  Q2: "New Zealand's Privacy Act 2020 governs data protection, enforced by the Office of the Privacy Commissioner (OPC). We flag every tool for Privacy Act compliance, data residency options within New Zealand, and OPC guidance on AI.",
  Q3: "New Zealand's economy has distinct AI priorities: agtech and precision agriculture for dairy, sheep and horticulture industries, geospatial and environmental AI for conservation and natural disaster management, tourism AI for New Zealand's visitor economy, creative AI in Wellington's film and game industry, and health AI for the public health system.",
  Q4: "New Zealand offers growing AI innovation support. Callaghan Innovation provides R&D grants and innovation funding. NZTE supports AI exports. The AI Forum of New Zealand coordinates ecosystem development. R&D tax credits of 15% benefit tech companies.",
  Q5: "New Zealand's AI regulatory framework includes the Privacy Act 2020 for data protection. Sector-specific regulations: Medsafe for health AI, RBNZ for financial AI. New Zealand's AI Guidelines published by the AI Forum set early standards. NZ participates in OECD AI policy discussions.",
  HERO_BADGE: "New Zealand-Focused",
  HERO_PITCH: "We rank every tool on Privacy Act compliance, NZD pricing, English-language support, and New Zealand tech ecosystem readiness — so you find tools built for NZ's unique market.",
  BADGES: 'English & Māori','NZD Pricing','Privacy Act Compliant','AgTech Hub NZ',
  WHY_HEADING: "Why New Zealand Needs Its Own AI Tool Directory",
  WHY_SUB: "New Zealand's AI ecosystem is unique — a highly digitized, innovation-focused economy with world-leading agtech, creative AI, and a uniquely Kiwi approach to responsible AI.",
  WHY_T1: "English & Māori",
  WHY_D1: "New Zealand is predominantly English-speaking with Te Reo Māori as an official language. Wellington is a growing creative tech hub. We flag every tool for NZ localization.",
  WHY_T2: "Privacy Act Compliance",
  WHY_D2: "New Zealand's Privacy Act 2020 governs data protection, enforced by the OPC. We evaluate tools for NZ data residency and OPC AI guidance.",
  WHY_T3: "AUCKLAND Tech Hub",
  WHY_D3: "New Zealand produces strong tech talent from University of Auckland, University of Waikato, and AUT. The AI Forum coordinates a growing AI ecosystem with strong agtech and creative AI focus.",
  CAT_SUB: "Top picks for New Zealand teams — rated for Privacy Act compliance, NZD pricing, and English-language support.",
  ECOSYSTEM_H2: "New Zealand's AI Ecosystem Is a Pacific Innovation Hub",
  ECOSYSTEM_P: "From Auckland's growing tech scene to Wellington's world-class creative AI, New Zealand combines a unique quality of life with deep expertise in agtech, geospatial AI, and creative technology.",
  CARD1_TITLE: "Auckland — New Zealand's Tech Capital 🇳🇿",
  CARD1_DESC: "Auckland is NZ's largest city and primary tech hub, home to the University of Auckland and AUT, plus a growing fintech, SaaS, and healthtech startup scene.",
  CARD2_TITLE: "Wellington — Creative Tech & GovTech 🎓",
  CARD2_DESC: "Wellington is NZ's creative tech capital, anchored by Victoria University and Weta Workshop/Digital. The city excels in film VFX, game development, and govtech AI.",
  CARD3_TITLE: "Christchurch — Emerging Innovation Hub 🏢",
  CARD3_DESC: "Christchurch is rebuilding as an innovation city, with the University of Canterbury driving agtech, geospatial AI, and civil engineering technology.",
  CARD4_TITLE: "AgTech & Environmental AI Hub 🔬",
  CARD4_DESC: "Callaghan Innovation provides R&D grants and innovation support. The AI Forum coordinates a growing AI ecosystem. NZ's unique environment (dairy, horticulture, conservation) drives specialized AI applications.",
  CTA_BADGE: "Built for New Zealand Founders, Researchers & Enterprises",
  CTA_H2: "Find the Right AI Tool for Your New Zealand Business",
  CTA_P: "No more guessing if a tool complies with the Privacy Act, supports NZ pricing, or works for Kiwi teams. Every tool on Apifeny AI is rated for NZ data compliance, NZD pricing, and English-language readiness.",
  SEO: "best AI tools in New Zealand 2026 · AI tools for NZ businesses · New Zealand AI software · AI writing tools New Zealand · AI coding tools NZ · AI marketing New Zealand · New Zealand AI directory · AI tools Auckland · AI tools Wellington · AI tools Christchurch",
});

addCountry('norway', {
  Q1: "Norway has a growing AI ecosystem with strong research at NTNU (Trondheim), University of Oslo, and the Norwegian Computing Center (NR). The startup scene centers on Oslo's burgeoning tech hub, Trondheim's deep tech ecosystem, and Bergen's energy and maritime AI cluster.",
  Q2: "Norway's Data Protection Act supplements EU GDPR (via the EEA Agreement) with Norwegian-specific provisions. The Norwegian Data Protection Authority (Datatilsynet) is highly active on AI guidance. We evaluate tools for Norwegian data residency, GDPR compliance, and Datatilsynet's AI guidance.",
  Q3: "Norway's economy has distinct AI priorities: oil and gas AI for offshore drilling and subsea operations, maritime and shipping AI for the world's 5th largest merchant fleet, renewable energy AI for hydropower and offshore wind, salmon farming AI for the world's largest seafood export industry, and health AI for Norway's public healthcare system.",
  Q4: "Norway offers extensive AI innovation support. The Research Council of Norway funds AI research through its IKTPLUSS program. Innovation Norway provides grants for AI commercialization. The Norwegian AI Strategy (2018) coordinates national AI efforts. Equinor's venture arm and the sovereign wealth fund support AI.",
  Q5: "Norway's AI regulatory framework combines EEA-relevant GDPR with the Norwegian Data Protection Act. Datatilsynet enforces AI-related privacy. Sector regulations: Norwegian Medicines Agency for health AI, Finanstilsynet for financial AI. Norway's National AI Strategy sets ethical guidelines.",
  HERO_BADGE: "Norway-Focused",
  HERO_PITCH: "We rank every tool on GDPR compliance, NOK pricing, Norwegian-language support, and Norwegian tech ecosystem readiness — so you find tools built for Norway's unique market.",
  BADGES: 'Norwegian & English','NOK Pricing','GDPR Compliant','Energy & Maritime AI',
  WHY_HEADING: "Why Norway Needs Its Own AI
